### ISSUE TITLE
Code highlighting

### ISSUE THREAD

**Issue by piranha** [russross/blackfriday#10]
It would be nice to be able to highlight code on server-side instead of doing that on client-side (right now I'm thinking about HTML and not Latex output). I see two possibilities here:
- get blocks of code from the resulting HTML (by parsing it), highlight them and inject back,
- provide (optional) highlighting function to blackfriday which will be called during rendering parts of the code.

I believe that latter is better option both API- and performance-wise. Do you have any thoughts/opinion about this?

**Comment by gaillard** [comment]
:thumbsup: for a future server side highlight :)

**Comment by shurcooL** [comment]
The [`github_flavored_markdown` renderer](https://github.com/russross/blackfriday#other-renderers) already does server-side highlighting for Go, diff file format and potentially other languages:

![image](https://cloud.githubusercontent.com/assets/1924134/7904980/20ae8c24-07c4-11e5-9a56-07f77aa57a60.png)

It uses these packages for performing server-side highlighting:

- https://github.com/sourcegraph/syntaxhighlight
- https://github.com/shurcooL/highlight_go
- https://github.com/shurcooL/highlight_diff

I think it's out of scope for `blackfriday` itself to be importing those packages. However, another higher-level package can import `blackfriday` and aforementioned highlighter packages and perform markdown rendering with code server-side highlighting.

**Comment by gaillard** [comment]
I see the complete html page example here https://godoc.org/github.com/shurcooL/github_flavored_markdown#example-Markdown--CompleteHtmlPage but doesn't that rely on non existing `.../github-flavored-markdown.css` file?

**Comment by shurcooL** [comment]
Yes, a .css with a highlighting scheme is needed. GitHub API provides a [Markdown rendering endpoint](https://developer.github.com/v3/markdown/), but it also expects you to bring .css yourself.

**Comment by egorsmkv** [comment]
@alecthomas created a nice library https://github.com/alecthomas/chroma 

It remains only to make the integration.

**Comment by Depado** [comment]
As shown in #396 I finally came up with this : https://github.com/Depado/bfchroma
(Hope that helps)
