### ISSUE TITLE
emphasis around code span doesn't render

### ISSUE THREAD

**Issue by radiofreejohn** [russross/blackfriday#113]
I'm not sure if this is because doing this is part of a Markdown extension that's not supported, or if I've done something wrong.

I made an example gist here: https://gist.github.com/radiofreejohn/6e068d82e6c848b5f3f5

It works as expected in GitHub, as well as in several other parsers, though that doesn't mean it should work here, but I wanted to see if there is something I was doing wrong.

The raw HTML of this after rendering with blackfriday is
```html
<blockquote>
<p>I want to test a **<code>code snippet</code>** with emphasis</p>
</blockquote>
```

Is this expected, or have I done something wrong?

**Comment by rtfb** [comment]
This is quite weird, I can not reproduce it. Neither with current code, nor with the code around the timeframe it was reported.

I tested with this:
```go

func TestBlockquoteCodeEmph(t *testing.T) {
	var tests = []string{
		"> Test **`bold code`**. Works?\n",
		"<blockquote>\n<p>Test <strong><code>bold code</code></strong>. Works?</p>\n</blockquote>\n",

		"> Test **`a * b`**. Works?\n",
		"<blockquote>\n<p>Test <strong><code>a * b</code></strong>. Works?</p>\n</blockquote>\n",
	}
	doTestsInline(t, tests)
}
```

@radiofreejohn, care to give it another go or should I just close it?

**Comment by rtfb** [comment]
Also, see #156, it might be related.

**Comment by radiofreejohn** [comment]
@rtfb thanks for looking into this – my old setup is long gone, probably safe to close this out since your test cases pass.
