### ISSUE TITLE
Link parsing doesn't correctly match URLs when they include brackets

### ISSUE THREAD

**Issue by buro9** [russross/blackfriday#116]
For a given piece of Markdown:
`[disambiguation](http://en.wikipedia.org/wiki/Disambiguation_(disambiguation))`

I would expect to see the output:
`<p><a href="http://en.wikipedia.org/wiki/Disambiguation_(disambiguation)">disambiguation</a></p>`

However blackfriday moves the second `)` outside of the link, thus breaking the URL:
`<p><a href="http://en.wikipedia.org/wiki/Disambiguation_(disambiguation">disambiguation</a>)</p>`

You can recreate this with this example code:

```go
package main

import (
	"fmt"

	"github.com/russross/blackfriday"
)

func main() {
	md := []byte(`[disambiguation](http://en.wikipedia.org/wiki/Disambiguation_(disambiguation))`)

	html := blackfriday.MarkdownCommon(md)

	fmt.Println(`Output  : ` + string(html))
	fmt.Println(`Expected: <p><a href="http://en.wikipedia.org/wiki/Disambiguation_(disambiguation)">disambiguation</a></p>`)
}
```

The correct output is generated by most other Markdown parsers, here's Pandoc as the online link makes it the easiest to share:
http://johnmacfarlane.net/pandoc/try/?text=[disambiguation]%28http%3A%2F%2Fen.wikipedia.org%2Fwiki%2FDisambiguation_%28disambiguation%29%29&from=markdown&to=html

Bracketed links are very popular on Wikipedia and a few other top-100 internet sites.

**Comment by SamuelDebruyn** [comment]
@miekg, can you do a PR to blackfriday with your fix?

**Comment by icco** [comment]
Yeah, I run into this almost daily still, right now I just go to http://dev.w3.org/html5/html-author/charref and hand replace parens, but it's not a great fix.

**Comment by cup** [comment]
https://github.com/russross/blackfriday/issues/116
https://github.com/russross/blackfriday/issues/123
https://github.com/russross/blackfriday/issues/291
https://github.com/russross/blackfriday/pull/222
https://github.com/russross/blackfriday/pull/356
https://github.com/russross/blackfriday/pull/358

**Comment by cup** [comment]
https://github.com/mmarkdown/mmark/issues/98
