### ISSUE TITLE
Multiple fenced code blocks inside a ">"-prefixed blockquote rendered incorrectly

### ISSUE THREAD

**Issue by anthonyfok** [russross/blackfriday#122]
Hello Russ,

Thank you very much for writing Blackfriday, as it is a very important Markdown engine for Go that makes easy blogging and super-fast rendering with Go applications like [Hugo](http://gohugo.io/) a possibility.

I think I may have stumbled across a bug in Blackfriday when I tried to nest multiple fenced (```) code blocks inside a ">"-prefixed blockquote section when I was experimenting with writing a blog entry a few days ago.

Here is a modified/shortened example:

#### Markdown source code:

----

<pre>
> Normally, `ls -l` shows the file date/time rounded to the nearest minute.  For example:
>
> ```sh
user@hostname:/etc/cups/ppd$ ls -l
-rw-r--r-- 1 root root 21279 Oct  8 18:07 FUJI-XEROX-DocuPrint-CM215-fw.ppd
-rw-r----- 1 root lp   21519 Oct  8 18:07 Xerox_WorkCentre_6015NI.ppd
```
>
> To find out the precise time when these PPD files were updated, we may use add the `--full-time` option to `ls`:
>
> ```sh
user@hostname:/etc/cups/ppd$ ls -l --full-time
-rw-r--r-- 1 root root 21279 2014-10-08 18:07:38.912867452 -0600 FUJI-XEROX-DocuPrint-CM215-fw.ppd
-rw-r----- 1 root lp   21519 2014-10-08 18:07:39.032869071 -0600 Xerox_WorkCentre_6015NI.ppd
```
>
> This may be used for comparing with the timestamps in /var/log/dpkg.log to pinpoint the exact package which changed the file permission and ownership of Xerox_WorkCentre_6015NI.ppd of my default printer.
</pre>

----

#### Expected result (rendered correctly by GitHub's Markdown engine):

----

> Normally, `ls -l` shows the file date/time rounded to the nearest minute.  For example:
>
> ```sh
user@hostname:/etc/cups/ppd$ ls -l
-rw-r--r-- 1 root root 21279 Oct  8 18:07 FUJI-XEROX-DocuPrint-CM215-fw.ppd
-rw-r----- 1 root lp   21519 Oct  8 18:07 Xerox_WorkCentre_6015NI.ppd
```
>
> To find out the precise time when these PPD files were updated, we may use add the `--full-time` option to `ls`:
>
> ```sh
user@hostname:/etc/cups/ppd$ ls -l --full-time
-rw-r--r-- 1 root root 21279 2014-10-08 18:07:38.912867452 -0600 FUJI-XEROX-DocuPrint-CM215-fw.ppd
-rw-r----- 1 root lp   21519 2014-10-08 18:07:39.032869071 -0600 Xerox_WorkCentre_6015NI.ppd
```
>
> This may be used for comparing with the timestamps in /var/log/dpkg.log to pinpoint the exact package which changed the file permission and ownership of Xerox_WorkCentre_6015NI.ppd of my default printer.

----

#### Actual result rendered by Blackfriday (commit 05b8cefd6a):

----

<blockquote>
<p>Normally, <code>ls -l</code> shows the file date/time rounded to the nearest minute.  For example:</p>

<p>```sh
user@hostname:/etc/cups/ppd$ ls -l
-rw-r&ndash;r&ndash; 1 root root 21279 Oct  8 18:07 FUJI-XEROX-DocuPrint-CM215-fw.ppd
-rw-r&mdash;&ndash; 1 root lp   21519 Oct  8 18:07 Xerox_WorkCentre_6015NI.ppd</p>
</blockquote>

<pre><code>&gt;
&gt; To find out the precise time when these PPD files were updated, we may use add the `--full-time` option to `ls`:
&gt;
&gt; ```sh
user@hostname:/etc/cups/ppd$ ls -l --full-time
-rw-r--r-- 1 root root 21279 2014-10-08 18:07:38.912867452 -0600 FUJI-XEROX-DocuPrint-CM215-fw.ppd
-rw-r----- 1 root lp   21519 2014-10-08 18:07:39.032869071 -0600 Xerox_WorkCentre_6015NI.ppd
</code></pre>

<blockquote>
<p>This may be used for comparing with the timestamps in /var/log/dpkg.log to pinpoint the exact package which changed the file permission and ownership of Xerox_WorkCentre_6015NI.ppd of my default printer.</p>
</blockquote>

----

#### HTML of the above Blackfriday output (commit 05b8cefd6a):

----

```html
<blockquote>
<p>Normally, <code>ls -l</code> shows the file date/time rounded to the nearest minute.  For example:</p>

<p>```sh
user@hostname:/etc/cups/ppd$ ls -l
-rw-r&ndash;r&ndash; 1 root root 21279 Oct  8 18:07 FUJI-XEROX-DocuPrint-CM215-fw.ppd
-rw-r&mdash;&ndash; 1 root lp   21519 Oct  8 18:07 Xerox_WorkCentre_6015NI.ppd</p>
</blockquote>

<pre><code>&gt;
&gt; To find out the precise time when these PPD files were updated, we may use add the `--full-time` option to `ls`:
&gt;
&gt; ```sh
user@hostname:/etc/cups/ppd$ ls -l --full-time
-rw-r--r-- 1 root root 21279 2014-10-08 18:07:38.912867452 -0600 FUJI-XEROX-DocuPrint-CM215-fw.ppd
-rw-r----- 1 root lp   21519 2014-10-08 18:07:39.032869071 -0600 Xerox_WorkCentre_6015NI.ppd
</code></pre>

<blockquote>
<p>This may be used for comparing with the timestamps in /var/log/dpkg.log to pinpoint the exact package which changed the file permission and ownership of Xerox_WorkCentre_6015NI.ppd of my default printer.</p>
</blockquote>
```

Note: These were rendered with the excellent **blackfriday-tool**.

I found a quick workaround by using indented code blocks, i.e. 1+4 spaces after the greater-than sign "`>`" (<code>&gt;&nbsp;</code> + <code>&nbsp;&nbsp;&nbsp;&nbsp;</code>).  Blackfriday renders these indented code blocks perfectly, albeit without syntax highlighting, which I don’t really need it for a simple `ls` output, so it is a very minor and definitely non-urgent bug for me.

But yes, it would be nice to have this little bug fixed eventually so that new users migrating existing Markdown to Blackfriday won’t be “surprised”.  :-)

Many thanks!

Anthony

**Comment by rtfb** [comment]
I just drilled to the bottom of it. Turns out this is a regression introduced with cd3fa08c (PR #56) while fixing #45. The problem is that when in a blockquote, the code that attempts to insert an extra newline in the `firstPass()` _before_ the fenced code block, is tricked into inserting that newline _after_ the code block.

Like this. Input markdown:

```
   0123 (column numbers)
1: > plain quoted text
2: > ```fenced
3: code
4: ```
5: > rest of quoted text
```

On line `2` it's supposed to detect the beginning of the fenced code, but since the fence doesn't start at column `0`, it fails and keeps going. Then it finds another fence sequence on line `4` and inserts a newline between `3` and `4`, which later confuses the loop in blockquote processor and it terminates too early.

So there are two things here:

1. We should probably come up with a better fix for #45, something not involving tampering with input in a pre-pass.
2. It seems like an extra newline at the end of a fenced code block within blockquote will cause trouble on its own and we need to address it.

**Comment by shurcooL** [comment]
Nicely investigated! :mag:

**Comment by rtfb** [comment]
Thanks, @shurcooL. Submitted PR #211 for all that.

**Comment by anthonyfok** [comment]
@rtfb, you are awesome!  Thank you so much!
