### ISSUE TITLE
Link parenthesis evaluation seems wrong.

### ISSUE THREAD

**Issue by icco** [russross/blackfriday#123]
The following markdown: `[Chef](https://en.wikipedia.org/wiki/Chef_(film))` evaluates to [Chef](https://en.wikipedia.org/wiki/Chef_%28film%29) here on Github, but blackfriday evaluates it to

``` html
<a href="https://en.wikipedia.org/wiki/Chef_(film">Chef</a>)
```

The code I'm using to evaluate this string is:

``` go
func Markdown(args ...interface{}) template.HTML {
  inc := []byte(fmt.Sprintf("%s", args...))
  inc = twitterHandleToMarkdown(inc)
  inc = hashTagsToMarkdown(inc)
  s := blackfriday.MarkdownCommon(inc)
  return template.HTML(s)
}

func twitterHandleToMarkdown(in []byte) []byte {
  return TwitterHandleRegex.ReplaceAll(in, []byte("$1[@$2](http://twitter.com/$2)"))
}

func hashTagsToMarkdown(in []byte) []byte {
  return HashtagRegex.ReplaceAll(in, []byte("$1[#$2](/tags/$2)"))
}
```

Thanks!

**Comment by cup** [comment]
https://github.com/russross/blackfriday/issues/116

https://github.com/russross/blackfriday/issues/123
https://github.com/russross/blackfriday/issues/291
https://github.com/russross/blackfriday/pull/222
https://github.com/russross/blackfriday/pull/356
https://github.com/russross/blackfriday/pull/358
