### ISSUE TITLE
Drop `sanitized_anchor_name` dependency

### ISSUE THREAD

**Issue by igungor** [russross/blackfriday#139]
Pulling russross/blackfriday brings the huge `github.com/shurcooL/go/` repo because this package needs a simple `sanitized_anchor_name.Create` function. It can be written easily. Please consider sticking to the standard library if possible. Thanks.

**Comment by shurcooL** [comment]
I agree that pulling in that large of a repository for this small need is not very justifiable.

I see some possible alternatives:

1. Moving the `sanitized_anchor_name` package out into a small separate git repository.
2. Moving the `sanitized_anchor_name` package into `blackfriday` repository itself (i.e., `github.com/russross/blackfriday/sanitized_anchor_name`).
3. Simply copying the code of `sanitized_anchor_name.Create` into private unexported code of `blackfriday` and using it internally.
    - With this approach, other packages that may want to use the same logic to create identical sanitized anchor names will not be able to reuse the logic.

It seems that the `sanitized_anchor_name` is now pretty feature-complete and stable, and I don't anticipate any changes/improvements to it in the future, so options 2 or 3 may work well. But I can't really predict that with full certainty.

**Comment by igungor** [comment]
both 2 and 3 sounds good.

**Comment by shurcooL** [comment]
Option 3 is not good because other packages import and rely on same logic, and they wouldn't have something to import if it's done.

**Comment by rtfb** [comment]
@shurcooL, since `sanitized_anchor_name` is your code, would you prefer option 1 or option 2? I think it's essentially your call.

**Comment by shurcooL** [comment]
I think let's go with option 1. Otherwise, if another package needs this logic, someone else can make the same argument:

> Pulling xyz brings the huge github.com/russross/blackfriday repo because this package needs a simple sanitized_anchor_name.Create function.

I can move it to `github.com/shurcooL/sanitized_anchor_name` or under another github username/organization, I don't mind. If that sounds good to everyone, I'll make the move and create a PR that closes this issue.

**Comment by rtfb** [comment]
`shurcooL/sanitized_anchor_name` sounds perfectly fine to me.
