### ISSUE TITLE
Extension proposal: ability to customize link HTML

### ISSUE THREAD

**Issue by trombonehero** [russross/blackfriday#143]
I'm using [Hugo](https://github.com/spf13/hugo) to generate websites, writing my content in Markdown format and running the results through various kinds of Go templates. I'd like to use Hugo's templating features to customize the HTML generated for links (e.g., to open off-site links in a new window), but that would require a hook in blackfriday to support user-defined HTML generation. The idea would be:
1. blackfriday allows callers to register a "format this link" callback
2. Hugo provides a callback that searches for user-defined templates
3. my template tells Hugo exactly how I want to format different kinds of links

Such a callback mechanism wouldn't affect the Markdown language at all and it wouldn't change the default behaviour, but it would allow significantly more flexibility for blackfriday clients. Might you be willing to consider such a mechanism?

**Comment by shurcooL** [comment]
I think you can do this without changes to blackfriday, by reusing its html renderer and overriding the link rendering behavior.

```Go
package main

import (
	"bytes"
	"fmt"
	"os"

	"github.com/russross/blackfriday"
)

func main() {
	text := []byte(`Title
=====

This is a [link](http://www.example.org/) being rendered in a custom way.
`)

	htmlFlags := 0
	renderer := &renderer{Html: blackfriday.HtmlRenderer(htmlFlags, "", "").(*blackfriday.Html)}

	extensions := 0
	// ...

	unsanitized := blackfriday.Markdown(text, renderer, extensions)
	os.Stdout.Write(unsanitized)
}

// renderer implements blackfriday.Renderer and reuses blackfriday.Html for the most part, except overriding Link rendering.
type renderer struct {
	*blackfriday.Html
}

func (r *renderer) Link(out *bytes.Buffer, link []byte, title []byte, content []byte) {
	fmt.Fprintf(out, "<custom link %q to %q>", content, link)
}
```

That generates the following (unsanitized) HTML:

```
<h1>Title</h1>

<p>This is a <custom link "link" to "http://www.example.org/"> being rendered in a custom way.</p>
```

**Comment by trombonehero** [comment]
I think you're right, that would support the intended use case: I've reported suggestion this back to Hugo's developers and will see how it goes from there. Thanks for making such an extensible system! Maybe there is something to this "Go" language if it makes it this easy. :)

**Comment by StefMa** [comment]
Hey @tomkwok sry that I dig up this old issue 😅.
But currently I search for exactly like what you want here.

I use hugo and want to "override" their markdown rendering.
> I've reported suggestion this back to Hugo's developers and will see how it goes from there.

Have you done this already?
I can't find something about this...
