### ISSUE TITLE
Ability to customize paragraph tags

### ISSUE THREAD

**Issue by alexcheninfo** [russross/blackfriday#153]
First of all, thanks for the good work. It's a beautiful Go package.

Some while ago you answered a question about someone who wanted to customize the anchor links. I tried doing the same for paragraph tags:

```
package main

import (
    "bytes"
    "fmt"
    "github.com/russross/blackfriday"
)

func main() {

input := []byte(`##Title

- another paragragh

This is a being rendered in a custom way.
`)

    htmlFlags := 0
    renderer := &renderer{Html: blackfriday.HtmlRenderer(htmlFlags, "", "").(*blackfriday.Html)}

    extensions := 0

    unsanitized := blackfriday.Markdown(input, renderer, extensions)
    os.Stdout.Write(unsanitized)
}

// renderer implements blackfriday.Renderer and reuses blackfriday.Html for the most part,
// except overriding Link rendering.
type renderer struct {
    *blackfriday.Html
}

func (options *renderer) Header(out *bytes.Buffer, text func() bool, level int, id string) {
    fmt.Fprintf(out, "<custom link %q to %q>", content, link)
}
```

The purpose of the code is to customize the `link` attributes of the output HTML.

I tried to do the same but with `p` tags:

```
func (options *renderer) Paragraph(out *bytes.Buffer, text func() bool) {
    fmt.Fprintf(out, "<p class='custom'>%q</p>", text)
}
```

But the output of the paragraph is just:

```
<p class='custom'>%!q(func() bool=0x80a15d0)</p>
```

Is there any way to customize the `p` tags?

**Comment by shurcooL** [comment]
`text()` is a func that returns a bool. It should be called in between the prefix and suffix.

I suggest you look at the default implementation of `Paragraph` method:

```Go
func (options *Html) Paragraph(out *bytes.Buffer, text func() bool) {
	marker := out.Len()
	doubleSpace(out)

	out.WriteString("<p>")
	if !text() {
		out.Truncate(marker)
		return
	}
	out.WriteString("</p>\n")
}
```

There may be more to worry about.

**Comment by alexcheninfo** [comment]
Oh, I see so there isn't an easy way to customize `p` tags?

**Comment by alexcheninfo** [comment]
Oh, I see so there isn't an easy way to customize `p` tags?

**Comment by alexcheninfo** [comment]
Oh, I see so there isn't an easy way to customize `p` tags?

**Comment by shurcooL** [comment]
Have you tried something like this?

```Go
func (*customRenderer) Paragraph(out *bytes.Buffer, text func() bool) {
	marker := out.Len()
	doubleSpace(out)

	out.WriteString("<custom paragraph>")
	if !text() {
		out.Truncate(marker)
		return
	}
	out.WriteString("</custom paragraph>\n")
}
```

**Comment by alexcheninfo** [comment]
Oh, yes. But I get:

`./file.go:44: undefined: doubleSpace`

I don't know what to do with that `doubleSpace`.

**Comment by shurcooL** [comment]
Yes, `doubleSpace` is a private helper that's defined in [`html.go`](https://github.com/russross/blackfriday/blob/77efab57b2f74dd3f9051c79752b2e8995c8b789/html.go#L853-L857) file.
