### ISSUE TITLE
Optional parameter to only allow image urls over SSL

### ISSUE THREAD

**Issue by aliaslam1992** [russross/blackfriday#154]
The link could be checked near these lines:

`if options.flags&HTML_SKIP_IMAGES != 0 {
        return
}`

Especially given the warnings shown when a non-HTTPS resource is loaded on a HTTPS site.

**Comment by shurcooL** [comment]
This seems like it might be out of scope for blackfriday, especially in the form of a flag... You can filter out non-https images via [`bluemonday`](https://github.com/microcosm-cc/bluemonday) in HTML sanitization stage. There might be other ways to achieve this too.

**Comment by rtfb** [comment]
OTOH, this sounds in tune with other requests to tweak the processing in some peculiar way, which makes me want blackfriday to have optional callbacks for such things. People could then provide those callbacks and do whatever exotic processing/filtering they need there. Some of our existing functionality could be redone this way, too.

**Comment by rtfb** [comment]
v2 has made customizing different bits of rendering like this super easy. I'm closing this out.
