### ISSUE TITLE
Add section map for result

### ISSUE THREAD

**Issue by bep** [russross/blackfriday#166]
This request comes from me and several feature requests raised on Hugo.

Maybe the API changes from this request will be too much for the current version, but please take this as input to Blackfriday 2.0.

The rendering is currently done somewhat in sections:
- header
  - table of contents
- body
  - footnotes
- footer

(the above may be incorrect, but it's good enough as an illlustration)

It is, to some extent, possible with embedding to get hold of the slice boundaries for some of these (I have tested it OK with the footnotes, the ToC is not possible as is).

Currently in Hugo we do some byte manipulations to extract the table of contents. This feels hackish and wastes cpu and memory. 

The main use cases we see are to get the table of contents and the footnotes as separate entities.

A single `[]byte` with some map with the different sections' upper and lower slice boundaries would be golden.

**Comment by rtfb** [comment]
Hey @bep, can you confirm v2's [Renderer interface](https://godoc.org/gopkg.in/russross/blackfriday.v2#Renderer) is enough to get this closed?

**Comment by bep** [comment]
@rtfb yea, that should do it. Looking forward to it; do you have an approximate time frame for the v2? I.e. "this year" or something?

**Comment by rtfb** [comment]
The release is already tagged: https://github.com/russross/blackfriday/releases/tag/v2.0.0 and good to use. I'm polishing up the documentation on the main README and that will be it.

**Comment by bep** [comment]
Ah, OK.
