### ISSUE TITLE
Extra newline at the end of each fenced code block line

### ISSUE THREAD

**Issue by onfoot** [russross/blackfriday#177]
Whenever I insert a fenced block into my markdown, each line contains an extra newline, which blows up the content unnecessarily.

In effect this:
```
for {
	ever()
}
```

becomes this:
```
<pre><code>
for {

	ever()

}

</code></pre>
```

I would happily make a pull request for this issue, but I'm not too familiar with blackfriday's codebase. 

In case it's a configuration issue after all, here's the code I initialize the library with:

``` go
	htmlFlags := 0
	htmlFlags |= blackfriday.HTML_USE_SMARTYPANTS
	htmlFlags |= blackfriday.HTML_SMARTYPANTS_FRACTIONS
	htmlFlags |= blackfriday.HTML_SMARTYPANTS_LATEX_DASHES
	renderer := blackfriday.HtmlRenderer(htmlFlags, "", "")
	extensions := 0
	extensions |= blackfriday.EXTENSION_NO_INTRA_EMPHASIS
	extensions |= blackfriday.EXTENSION_TABLES
	extensions |= blackfriday.EXTENSION_FENCED_CODE
	extensions |= blackfriday.EXTENSION_AUTOLINK
	extensions |= blackfriday.EXTENSION_STRIKETHROUGH
	extensions |= blackfriday.EXTENSION_SPACE_HEADERS
	extensions |= blackfriday.EXTENSION_HEADER_IDS

	md := blackfriday.Markdown(contentBuffer.Bytes(), renderer, extensions)
```

Thanks!

**Comment by shurcooL** [comment]
Are you running the current version of `blackfriday`?

I cannot reproduce. [This program](http://play.golang.org/p/FL_LKYKy69) produces output without additional newlines in the fenced code block:

```
<p>Hi.</p>

<pre><code>for {
    ever()
}
</code></pre>

<p>Bye.</p>
```

**Comment by onfoot** [comment]
I just took *another* look at my code that prepares the markdown for blackfriday and it turned out that it was actually a bug on my side. Sorry about that! Thanks for the quick response!

**Comment by shurcooL** [comment]
No problem and happy to help! :)
