### ISSUE TITLE
Leading tab throws off header

### ISSUE THREAD

**Issue by apoydence** [russross/blackfriday#179]
```
package main

import (
        "github.com/russross/blackfriday"
	"fmt"
)

func main() {
	input := []byte(`\t#Some Header`)
	output := blackfriday.MarkdownBasic(input)
	fmt.Println(string(output))
}
```

yields:

```
<p>\t#Some Header</p>
```

Where I would have expected:
```
<h1>Some Header</h1>
```

**Comment by JackKnifed** [comment]
[The spec](http://daringfireball.net/projects/markdown/syntax#header) seems to suggest to me that the line has to start with `#`. So, no whitespace, no tabs, no `\t`.

> Atx-style headers use 1-6 hash characters at the start of the line, corresponding to header levels 1-6.

It looks like it's inheriting this header format from [atx](http://www.aaronsw.com/2002/atx/intro) where they also say, specifically:

> Headings start with 1 or more # characters.

If whitespace is not allowed, `\t#Some Header` not be a valid header?

**Comment by apoydence** [comment]
Is this only for #header or would others fall into this as well?

**Comment by JackKnifed** [comment]
Keep in mind, I'm likely butchering everything with the names and syntax here, and there's probably some I'm wrong with. This is how I understand it though, and it works for me. Bear with me.

There's two types of elements - block elements and inline elements. Block elements take up a line, or multiple lines, and the whole line is that thing. Inline elements can span lines, and have a starting bit and an ending bit.

When you look at block elements, the spec defines a few:

* Paragraphs and line breaks (w/e, that's just weird)
* Headers
* Blockquotes
* Lists
* Horizontal Rules

Headers are defined like that.

Blockquotes are not defined that well like this. If you put a space in front of a blockquote, I don't think it's supposed to work, but then again most of the places where I use it, it does. The closest quote I could come up with is below:

> It looks best if you hard wrap the text and put a > before every line

Nested blockquotes *should* be:

```
> this is level 1
> > this is level 2
> > > this is level 3
> this is level 1
> > this is level 2
```

However, I've seen different markdown parsers use spaces before as quoting levels - you can nest other block elements within a blockquote.

I don't see anything in the spec about spaces in front of lists. I could've swore it's there though - that's how lists are indented.

If you're going to do the spaced codeblocks, you need 4 spaces before your code. I always use the three backticks though - it's cleaner. If you're going to do that, the three backticks are the only thing on the line - no spaces before or after - at least every time I do it. Now that I look at it, I don't see the three backticks in the markdown spec though.

For horizontal rules, proper markdown is to not have a space before the first character. IDK what different libraries do though. I just never put a space there.

**Comment by shurcooL** [comment]
> Now that I look at it, I don't see the three backticks in the markdown spec though.

It's in GitHub Flavored Markdown, see [Fenced Code Blocks](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks).

**Comment by JackKnifed** [comment]
TY - it's good to know that I'm not just crazy :-)

**Comment by rtfb** [comment]
The original complain is WAD and if I'm reading the discussion close enough, there's nothing to add. Closing.
