### ISSUE TITLE
Newline required after last "reference style link" or it is not parsed.

### ISSUE THREAD

**Issue by bramp** [russross/blackfriday#180]
```go
var test = "[Something][1]\n[1]: http://blah.com"

output := blackfriday.MarkdownCommon([]byte(test))
fmt.Printf(string(output))
```
produces:
```
<p>[Something][1]
[1]: <a href="http://blah.com">http://blah.com</a></p>
```

but
```go
var test = "[Something][1]\n[1]: http://blah.com\n"
```

correctly produces: ```<p><a href="http://blah.com">Something</a></p>```

The difference is the `\n` at the end of the test string. Is the Markdown text required to end with a new line? Unless I'm missing a good reason, could we make the parsing more lack, and not require the \n at the end?

**Comment by shurcooL** [comment]
> Unless I'm missing a good reason, could we make the parsing more lack, and not require the \n at the end?

I agree, it'd be better not to require it.
