### ISSUE TITLE
Fenced Code Block -> html, language definition not working

### ISSUE THREAD

**Issue by db-tech** [russross/blackfriday#183]
For some reason, if i try to generate a html \<pre\>\<code\> block with fenced code, the language definition is not available in the class.
for example, if starting a code with (``` go), I will not get  (\<code class="language-go"\>) but instead this:  (\<pre\>\<code\>).

The strange thing is, i checked the method BlockCode within html.go, and the correct line (269 -> out.WriteString("\<pre\>\<code class=\"language-") ) is executed!
Am I missing something ?

**Comment by shurcooL** [comment]
It'd be helpful if you could post a complete source.

**Comment by db-tech** [comment]
I'll try...

I am using the beego framework. This is what I am doing in the controller file:
```go
	textUnsafe := blackfriday.MarkdownCommon([]byte(blog.Content))
	textSafe := bluemonday.UGCPolicy().SanitizeBytes(textUnsafe)
	blog.Content = string(textSafe[:])
       ...
```
blog.Content holds the markdown string. I've checked the string and its exactly what its supposed to be. 

Within the html file I am using templating and the beego specific function `str2html` to print the html code:
```
{{str2html .BLOG.Content}}
```

I am having a little bit trouble to display the markdown code in this makdown editor :-), so here are the pastebin links.

markdown source:
http://pastebin.com/S8Gj5vYn

This is what the result looks like:
http://pastebin.com/vpHgdKmm

**Comment by shurcooL** [comment]
You're using `bluemonday.UGCPolicy()`, which does not allow class attribute in code elements.

```Go
package main

import (
	"fmt"

	"github.com/microcosm-cc/bluemonday"
	"github.com/russross/blackfriday"
)

func main() {
	in := []byte("```" + ` go
func fact(n int) int {
  if n <= 1 {
    return n
  }
return n * fact(n-1)
}
` + "```")

	out := blackfriday.MarkdownCommon(in)

	fmt.Println(string(out))

	safe := bluemonday.UGCPolicy().SanitizeBytes(out)

	fmt.Println(string(safe))
}
```

If you run the above, you'll see it's initially `<pre><code class="language-go">` and after sanitizing it becomes `<pre><code>`.

To fix your problem, you should replace:

```Go
textSafe := bluemonday.UGCPolicy().SanitizeBytes(textUnsafe)
```

With:

```Go
policy := bluemonday.UGCPolicy()
policy.AllowAttrs("class").Matching(bluemonday.SpaceSeparatedTokens).OnElements("code")
textSafe := policy.SanitizeBytes(textUnsafe)
```

**Comment by db-tech** [comment]
Wow, thanks.. so obvious..
I was so sure I did check the outcome without the sanitizer but seems like i've maybe changed the wrong controller method.

Anyway, many thanks for that !!

Now i works perfectly, issue can be closed.
