### ISSUE TITLE
Latex needs to escape `#` at least in titles

### ISSUE THREAD

**Issue by tv42** [russross/blackfriday#185]
```console
$ cat sample.md
# You will always be my #1
$ blackfriday -latex sample.md sample.tex && pdflatex sample.tex
[...]
! Illegal parameter number in definition of \GetTitleStringResult.
<to be read again> 
                   1
l.26 \section{You will always be my #1}
                                       
? 
```

Escaping it as `\#` is the trick (via http://suchideas.com/articles/computing/latex/errors/ )

```
$ perl -pi -e 's/my #1/my \\#1/' sample.tex
$ grep my sample.tex
\section{You will always be my \#1}
$ pdflatex sample.tex 
[no error]
```

**Comment by russross** [comment]
The LaTeX backend is just a simple hack, and I'm sure there are lots of other things that don't work. In this case, there is already a list of characters that require backslash-escaping. I've added the hash mark to the list. The LaTeX backend does not have tests like the HTML backend, so I'm crossing my fingers and hoping that didn't break anything else.

**Comment by tv42** [comment]
Thank you, this seems to work well for me. I couldn't find the escaping code myself, with just quick skimming of the source..
