### ISSUE TITLE
Fails to parse correctly with combined tags

### ISSUE THREAD

**Issue by faxal** [russross/blackfriday#186]
This does not work:
`####Example`

This works:
`#### Example`

Most markdown editors renders `#### Example`  to `<h4>Example</h4>`

**Comment by shurcooL** [comment]
Hi @faxal,

blackfriday already supports this. You'll need to configure it appropriately.

Take a look at [`EXTENSION_SPACE_HEADERS`](https://godoc.org/github.com/russross/blackfriday#EXTENSION_SPACE_HEADERS) extension, you'll want it disabled. It's on by default in `MarkdownCommon` helper.

```Go
    EXTENSION_SPACE_HEADERS     // be strict about prefix header rules
```

**Comment by faxal** [comment]
@shurcooL :+1:  I was just going through the source and figured this. 

Thanks, I'll see myself out.
