### ISSUE TITLE
Question: Fenced Code Block lang

### ISSUE THREAD

**Issue by manfer** [russross/blackfriday#188]
In the README it says:

> Fenced code blocks. In addition to the normal 4-space indentation to mark code blocks, you can explicitly mark them and supply a language (to make syntax highlighting simple)

I added `EXTENSION_FENCED_CODE` and the output is just inside `<pre><code>` tags. But there is nothing about syntax highlighting in the output. Not even something I can use, for example a lang attribute added.

What else I have to do?

**Comment by shurcooL** [comment]
Did you specify the language when creating a fenced code block? blackfriday does not auto detect it. For example:

    ```Go
    func foo() {}
    ```

That should set "lang" attribute to "Go".

However, blackfriday's HTML renderer does not perform syntax highlighting in the backend. You either have to do it in frontend, add a backend highlighter yourself, or consider using [GitHub Flavored Markdown renderer](https://godoc.org/github.com/shurcooL/github_flavored_markdown) that has some syntax highlighting support already added (for Go and diff file formats).

**Comment by manfer** [comment]
@shurcooL Thanks. Knowing that it should output something was what I wanted to know. With that info now I have made some tests and I see that it outputs a class in the code tag. I now have to debug the code that doesn't output that class. There is some postprocessing so for sure somewhere is removing that class.

**Comment by shurcooL** [comment]
It's possible HTML sanitization is doing it, unless you specifically whitelist class tag and allowed values for it.
