### ISSUE TITLE
List causes infinite loop when Renderer does not invoke callback

### ISSUE THREAD

**Issue by mholt** [russross/blackfriday#189]
We've implemented a custom Renderer for our project where we only render a few elements, and lists are not one of them. Thus we implement the List method like this:

``` go
func (r SummaryRenderer) List(out *bytes.Buffer, text func() bool, flags int) {}
```

i.e. a no-op.

However, this causes infinite loop in blackfriday because `text()` isn't called. The [internal list method](https://github.com/russross/blackfriday/blob/8cec3a854e68dba10faabbe31c089abf4a3e57a6/block.go#L1051-L1069) returns 0, meaning that [the input cursor is not advanced](https://github.com/russross/blackfriday/blob/8cec3a854e68dba10faabbe31c089abf4a3e57a6/block.go#L155-L157) so it keeps hitting the same part of the input again and again.

If this is intended/normal, is there a good way to skip list elements, or what would you propose to fix this?

Related issue: https://github.com/mholt/caddy/issues/211

**Comment by shurcooL** [comment]
Related issue #106.

**Comment by jbowens** [comment]
I just ran into this. I solved it by calling `text()` but always truncating the buffer back to its original position:

```go
func (_ snippetRenderer) List(out *bytes.Buffer, text func() bool, _ int) {
	v := out.Len()
	text()
	out.Truncate(v)
}
```
https://github.com/jbowens/www/blob/master/blog/snippet.go

**Comment by rtfb** [comment]
With v2, doing this is now easy:

```go
func (r *listlessRenderer) RenderNode(w io.Writer, node *bf.Node, entering bool) bf.WalkStatus {
	if node.Type == bf.List {
		return bf.SkipChildren
	}
	return r.defR.RenderNode(w, node, entering)
}
```
(a complete example of a similar customization can be found here: https://gist.github.com/rtfb/f0ad5013f4c3068b592da205b6542db9)
