### ISSUE TITLE
Checkboxes

### ISSUE THREAD

**Issue by JackKnifed** [russross/blackfriday#192]
I just noticed - checkboxes are a part of GFM but not a part of blackfriday:

https://github.com/blog/1375%0A-task-lists-in-gfm-issues-pulls-comments

Is this worthwhile? I think List() in html.go would have to be modified - you'd have to capture the checked status of that box, so you have to pass that value to that function. I run a [fork of blackfriday myself](https://github.com/JackKnifed/blackfriday) in which I added stuff to quotes per issue #160 - so I could make those changes easier, but I don't even know if it's worth the effort.

IDK, I was wondering if this is something someone would want?

**Comment by shurcooL** [comment]
`blackfriday` is a general, customizable Markdown library. If you want GFM specifically, use [`github_flavored_markdown`](https://github.com/russross/blackfriday#other-renderers) package. It [supports task lists](https://github.com/shurcooL/github_flavored_markdown/issues/6) and other GFM-specific features.

**Comment by JackKnifed** [comment]
I did not see this, I'll have to double back and look at this further.

ty

**Comment by shurcooL** [comment]
You're welcome!
