### ISSUE TITLE
Footnotes are not rendered following an exclamation point

### ISSUE THREAD

**Issue by jlengstorf** [russross/blackfriday#194]
When placing a footnote after a sentence with an exclamation point, the footnote is not rendered properly.

Example:
```
Something exciting![^fn1]

[^fn1]:
  This is a footnote.
```

Output:
```html
<p>Something exciting![^fn1]</p>
```

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[blackfriday] Footnotes are not ren..." ]
>When placing a footnote after a sentence with an exclamation point, the footnote is not rendered properly.
>
>Example:
>```
>Something exciting![^fn1]
>
>[^fn1]:
>  This is a footnote.
>```
>
>Output:
>```html
><p>Something exciting![^fn1]</p>
>```

It is seen as an image, as a work around you can put a space between the `!` and
the deferred footnote.

/Miek

--
Miek Gieben

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[blackfriday] Footnotes are not ren..." ]
>When placing a footnote after a sentence with an exclamation point, the footnote is not rendered properly.
>
>Example:
>```
>Something exciting![^fn1]
>
>[^fn1]:
>  This is a footnote.
>```
>
>Output:
>```html
><p>Something exciting![^fn1]</p>
>```

Some ala this solves it:

```
diff --git a/inline.go b/inline.go
index cbd0b84..f50963b 100644
--- a/inline.go
+++ b/inline.go
@@ -259,7 +259,18 @@ func link(p *parser, out *bytes.Buffer, data []byte, offset int) int {
         // [-@text] == citation, add to reference, but suppress output
         var t linkType
         if offset > 0 && data[offset-1] == '!' {
-               t = linkImg
+               if len(data)-1 <= offset {
+                       t = linkImg
+               } else {
+                       switch data[offset+1] {
+                       case '^':
+                               // We seen ![^...], this is *not* an image, but a footnote
+                               // that will start on the next char.
+                               t = linkDeferredFootnote
+                       default:
+                               t = linkImg
+                       }
+               }
```

This won't apply cleanly to Blackfriday, 'cause I'm working on a fork here.

/Miek

--
Miek Gieben
