### ISSUE TITLE
Please consider tagging a new release

### ISSUE THREAD

**Issue by anthonyfok** [russross/blackfriday#198]
Hello @russross,

Sorry to bother you again.  It has been over a year since the v1.2 release, and I was wondering if you are considering making a new release in the near future, considering that there has been considerable enhancements in the past year, including new additions to the Blackfriday API that Go applications like Hugo depend on.

Having a new release also helps with [Debian packaging of Blackfriday](http://anonscm.debian.org/cgit/pkg-go/packages/golang-blackfriday.git) (and presumably for Fedora too).  For example, we have a [debian/watch](http://anonscm.debian.org/cgit/pkg-go/packages/golang-blackfriday.git/tree/debian/watch) file that helps monitor GitHub for new releases, prompting us Debian pkg-go maintainers to upgrade.  To see it in action, please visit http://pet.debian.net/pkg-go/pet.cgi and search for "blackfriday" on that page.

So, at the urging of @tianon, an administrator of our [Debian Go Packaging Team](https://alioth.debian.org/projects/pkg-go), I am submitting this issue for your kind consideration.

Many thanks!

Anthony

**Comment by russross** [comment]
I've tagged a v1.3 release with all the changes from the past year. Hope that helps!

**Comment by tianon** [comment]
Thanks @russross! :heart:
