### ISSUE TITLE
EXTENSION for LaTeX equations surrounded by `$` or `$$`?

### ISSUE THREAD

**Issue by yuntan** [russross/blackfriday#199]
When I parse markdown text including LaTeX equation surrounded by `$` or `$$`

```go
package main

import (
	"fmt"
	"github.com/russross/blackfriday"
)

func main() {
	output := blackfriday.MarkdownCommon([]byte(`sample $x^y_z$ text _italic_`))
	fmt.Println(string(output))
}
```

I got

```html
<p>sample $x^y<em>z$ text _italic</em></p>
```

What I expected is 
```html
<p>sample $x^y_z$ text <em>italic</em></p>
```

`$` and `$$` is common syntax for inline and block LaTeX equation used by MathJax. We need some option for these syntax.

**Comment by russross** [comment]
If I remember right, there are a couple of options to work around this particular problem:

1. Use the EXTENSION_NO_INTRA_EMPHASIS option, which will prevent the underscore between the y and z from being parsed as an emphasis marker.

2. Put a backslash in front of the underscore in question. This will escape it as a literal symbol (for parsing purposes) so it will pass through unmolested.

As currently structured, the parser does not know that you are using LaTeX as your renderer, so it cannot make changes to the parsing behavior. Markdown was designed to integrate with HTML, so there are likely to be other problems with the LaTeX integration for serious use.

In general, the LaTeX renderer was just an experiment. If you are interested in taking it over, it could use some attention. It would probably make sense to split it into a separate project.

**Comment by yuntan** [comment]
Use EXTENSION_NO_INTRA_EMPHASIS option don't work for this problem. `MarkdownCommon` uses the option but doesn't works. And the option will not work for some equation like `$x^y _zw_ v $`.

Putting backslashes in front of the underscores is pain for users. 

Pandoc markdown parser treat `$` and `$$` as LaTeX math by default. For example,

```
$ echo 'sample $x^y_zv_w$ text'|pandoc -f markdown -t html --mathjax
<p>sample <span class="math inline">\(x^y_zv_w\)</span> text</p>
$ echo '$$x^y_zv_w$$'|pandoc -f markdown -t html --mathjax
<p><span class="math display">\[x^y_zv_w\]</span></p>
```

**Comment by shurcooL** [comment]
As Russ said, the LaTeX renderer is experimental and not well supported. If you're interested in working on it, it's best to do that by moving it out into a separate repo and working on it there.

**Comment by yuntan** [comment]
OK, I'd implemented what I want in my fork. Sorry for disturbing you.

**Comment by Honghe** [comment]
Maybe this is a better solution, add an option to prohibit rendering of texts in math block, such as `$ e=mc^2 $` or `$$ e=mc^2 $$`, so we can use other `Latex math` javascript engine, like [Katex](https://github.com/Khan/KaTeX), to render the math in `$ e=mc^2 $` or `$$ e=mc^2 $$` from the html output of `blackfriday`.
