### ISSUE TITLE
Auto add tag p when build markdown 

### ISSUE THREAD

**Issue by hoavo** [russross/blackfriday#200]
My markdown : `![alt text](imagelink){.center}`
html after build:`<p><img src="imagelink" alt="altex">{.center}</p>`
Please help me, i waste a lot of time on it

**Comment by shurcooL** [comment]
This is normal Markdown behavior.

Given a simple sentence like `Hello there.`, it will become a single paragraph `<p>Hello there.</p>`.

Given two sentences like this:

```Markdown
Hi.

Bye.
```

That will become 2 paragraphs:

```HTML
<p>Hi.</p>

<p>Bye.</p>
```

**Comment by hoavo** [comment]
Thanks, it's right, how i can add style for tag image. I try to do it but not possible

**Comment by shurcooL** [comment]
I'm not aware of that being a part of Markdown.

**Comment by hoavo** [comment]
Thanks for your helps.
