### ISSUE TITLE
Option to disable quote mangling and/or &'s

### ISSUE THREAD

**Issue by teran-mckinney** [russross/blackfriday#209]
It'd be nice if the quote conversion in blackfriday could be disabled, so " would be " and not &ldquo. Possibly the same for &.

I may attempt this unless one of someone else gets to it first.

**Comment by shurcooL** [comment]
Are you familiar with [`HTML_USE_SMARTYPANTS`](https://godoc.org/github.com/russross/blackfriday#HTML_USE_SMARTYPANTS) option?

If I understand what you're looking for correctly, not using that option will get you what you want. Does that help?

**Comment by teran-mckinney** [comment]
My bad, thank you! I've been only using blackfriday through Hugo. I looked through the blackfriday source and it seemed there was no way to disable it, but evidently missed a lot.

I'll see how I can switch to MarkdownBasic in hugo.
