### ISSUE TITLE
Please tag new release v1.4 in the near future

### ISSUE THREAD

**Issue by anthonyfok** [russross/blackfriday#213]
Hi @russross, it is that time again.  :-)

Cc: @tianon

Since @rtfb has kindly merged #190 to add `HTML_SMARTYPANTS_DASHES` flag, a feature that Hugo now depends on (spf13/hugo#1327), it would be great a new release of blackfriday could be tagged to facilitate Debian packaging of the new blackfriday.  :-)

I see that @rtfb's recent pull request #211 (to fix #122) is pending, so perhaps it would be a good idea wait until #211 is merged before releasing v1.4.  (Are there other pending fixes?)

Many thanks!

Cheers,
Anthony

P.S. For completeness sake: the previous release tagging request was at #198.

**Comment by anthonyfok** [comment]
Now that #211 is merged, how about tagging v1.4 now?  :-)

**Comment by russross** [comment]
Done.

**Comment by anthonyfok** [comment]
You are awesome!  Many thanks Russ!
