### ISSUE TITLE
A markdown file doesn't show how it should

### ISSUE THREAD

**Issue by xxxtonixxx** [russross/blackfriday#227]
- Original file in Github:
[Original file](https://github.com/oslugr/curso-git/blob/master/texto/Modulos.md)

- Mirror to repository of Github, it's same file:
[Mirror file](https://try.gogs.io/xxxtonixxx/curso-git/src/master/texto/Modulos.md)

This issue was reported in the gogs' repository [#2226](https://github.com/gogits/gogs/issues/2226)

Saludos and sorry for my bad english! :+1: :smile:

**Comment by shurcooL** [comment]
This isn't a bug in blackfriday, it's a configuration issue. Blackfriday offers configuration options for parsing Markdown. For example, there are extensions like `EXTENSION_SPACE_HEADERS` and `EXTENSION_NO_EMPTY_LINE_BEFORE_BLOCK` that will affect how certain Markdown documents get parsed.

What's happening here is that gogs did not configure blackfriday to exactly match the way GitHub parses Markdown.

I can see in https://github.com/gogits/gogs/issues/2226 that gogs has no plans to change their configuration, so your best bet is to use a more portable format format.

More specifically, you're not putting a space between `#` and the header title:

```
##Introducción
```

That should be:

```
## Introducción
```

Adding those spaces should let the gogs Markdown parser configuration work as you'd expect.

**Comment by xxxtonixxx** [comment]
Ok, good info, thank you very much!!! :smile:
