### ISSUE TITLE
Ability to get ListItems in the order of appearance?

### ISSUE THREAD

**Issue by bobbytables** [russross/blackfriday#230]
I'm attempting to create a tree data structure containing list items using blackfriday, but it seems to call `ListItem` on my `renderer` interface for nested items first. Is this a bug or intended functionality?

**Comment by shurcooL** [comment]
I think lists are rendered in a depth-first manner. The nested lists are rendered into a buffer first.

Making this API simpler and easier to work with would be a part of #218 I think.

**Comment by rtfb** [comment]
@bobbytables, are you still interested in this? A few weeks back I've progressed the `v2` branch enough for it to be workable, it might've solved your problem. Want to give it a try?
