### ISSUE TITLE
Adjacent ordered and unordered lists merged

### ISSUE THREAD

**Issue by moorereason** [russross/blackfriday#235]
Given the following markdown content:

```text
- First
- Last

1. First
2. Last
```

`blackfriday` renders

```text
<ul>
<li>First</li>

<li><p>Last</p></li>

<li><p>First</p></li>

<li><p>Last</p></li>
</ul>
```

I would expect it to render as:

```text
<ul>
<li>First</li>
<li>Last</li>
</ul>

<ol>
<li>First</li>
<li>Last</li>
</ol>
```

**Comment by shurcooL** [comment]
I think this is a problem with Markdown, not with blackfriday. Blackfriday is going the right thing according to what Markdown suggests (it's not a very precise specification though).

**Comment by moorereason** [comment]
I haven't looked at the code to see how difficult it would be, but would you accept an optional extension to fix this issue?

**Comment by rtfb** [comment]
Looking at the surface, it seems like something that's fixable and not interfering with other things, so if you want to give it a go, I would consider it for a merge.

**Comment by tianon** [comment]
I think this might have broken parsing of nested lists too.  Here's some example code that's not rendering properly anymore:

```markdown
## Run Redmine with a Database Container

Running Redmine with a database server is the recommened way.

1.	start a database container

	-	PostgreSQL

	-	MySQL (replace `--link some-postgres:postgres` with `--link some-mysql:mysql` when running redmine)

2.	start redmine
```

```html
<p>Running Redmine with a database server is the recommened way.</p>

<ol>
<li>start a database container</li>
</ol>

<pre><code>-   PostgreSQL

-   MySQL (replace `--link some-postgres:postgres` with `--link some-mysql:mysql` when running redmine)
</code></pre>

<ol>
<li>start redmine</li>
</ol>
```

Here's how GitHub renders that block: (and blackfriday, up until recently)

## Run Redmine with a Database Container

Running Redmine with a database server is the recommened way.

1.	start a database container

	-	PostgreSQL

	-	MySQL (replace `--link some-postgres:postgres` with `--link some-mysql:mysql` when running redmine)

2.	start redmine

**Comment by tianon** [comment]
(and the source document for that section is https://github.com/docker-library/docs/blob/d2bdba0e8f201164aab29274692630f8dd9607af/redmine/content.md#run-redmine-with-a-database-container, since the tabs don't translate correctly to a comment in GitHub)

**Comment by tianon** [comment]
(and a link to our failing `markdownfmt` which is how we noticed the change: https://travis-ci.org/docker-library/docs/builds/128108377#L173)

**Comment by kaushalmodi** [comment]
This works:

```
- First
- Last

<!-- any comment -->

1. First
2. Last
```

**Comment by mistyhacks** [comment]
I am still seeing this bug, as well as other bugs to do with list handling.

Breaking up two numbered lists with a comment as above does not work (it does work for bullet lists).  Here is a reproducer. The second `1.` item is rendered as `4.`

```markdown
1.  This is a list item
2.  This is another list item in the same list. The number you use in Markdown
    does not necessarily correlate to the number in the final output. By
    convention, we keep them in sync.
3.  For single-digit numbered lists, using two spaces after the period makes
    interior block-level content line up better along tab-stops.

    <!-- separate lists -->

1.  This is a new list. With Hugo, you need to use a HTML comment to separate two
      consecutive lists.
```

In addition, nested bullet lists 3 levels deep do not work for me. The triply-nested elements just show up as doubly-nested, at the same level as their parents. Here's a reproducer. The sub-sub-item just shows up as the same level as its parent.

```markdown
- This is a list item
* This is another list item in the same list
- You can mix `-` and `*`
  - To make a sub-item, indent two spaces.
    - This is a sub-sub-item.
  - Another sub-item.
```

Finally, list items that contain block-level elements within them render the block-level elements outside of the list item, at the same level as the list's `<ul>` tag. Here's a reproducer. The paragraph and the code block both show up outside of the list, and the list item after them just starts a new list.

```markdown
- Bullet lists can have paragraphs or block elements within them.

  Just indent the content to be even with the text of the bullet point, rather
  than the bullet itself.

  ```bash
  ls -l
  ```
  
  - And a sub-list after some block-level content
```

**Comment by mistyhacks** [comment]
I can't seem to edit my comment above, but the final code block is not missing its closing fence. Github is eating it and not closing the markdown block correctly.

**Comment by mistyhacks** [comment]
OK, so lists should be indented 4 spaces and not the (somewhat standard) 2? How about indenting code blocks by using 4 spaces, like is very standard across Github etc? That would break with this? Does that need like 6 spaces? 8?

In general should we be using 4 spaces to indent, rather than always 2? Where are these "rules" set out? I am trying to actually document this so our users will understand what to do and it's just not "If it's broken try adding another layer of indents!"
