### ISSUE TITLE
HTML code will be wrapped with <p> tag. Can we disable it?

### ISSUE THREAD

**Issue by crispgm** [russross/blackfriday#237]
my input is simple html
but would be wrapped with <p> tag
how can I remove that?

**Comment by rtfb** [comment]
In general it shouldn't, but there are cases where the parser is powerless to guess correctly where plain html begins and/or ends and thus treats it as plain text. Can you provide some exact repro cases?

**Comment by crispgm** [comment]
@rtfb I use blackfriday as lib to generate static sites
So my markdown file contains HTML header and footer code segments
The HTML codes are pretty complex and real

**Comment by rtfb** [comment]
OK, I guess I know the problem. When Blackfriday encounters something that looks like html tag, it checks it against a whitelist, which does not include things like `<html>`, `<head>`, `<meta>` and such. If the tag is whitelisted, it's recognized as such and being rendered accordingly. If it's not, it's being treated as plain text (and thus, wrapped in a paragraph).

Simply whitelisting more tags is easy, but I wonder if that would be enough. Please provide a sample of your use case (cut some non-essential bits if it's too large).

**Comment by crispgm** [comment]
`
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="keywords" content="crispgm, crisp blog"/>
        <meta name="description" content="Crisp Blog"/>
        <title>Crisp Blog</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="/style.css" media="screen">
        <script src="/script/highlight.pack.js"></script>
        <script src="/script/jquery-2.0.3.min.js"></script>
        <script>hljs.initHighlightingOnLoad();</script>
    </head>
    <body>
        <div id="menu">
            <div id="menu_home">
                <a href="/" style="color: #000000;">DAVID ZHANG</a>
            </div>
            <div id="menu_links">
                <span class="menu_item"><a href="/archive.html">ARCHIVE</a></span>
            </div>
        </div>
    </div>
    <div id="container">
    ### Hello, world
    </div>
    <div id="footer">
    ......
`

@rtfb the stuff is like this
and actually there is another problem that <!DOCTYPE html> would be escape into &lt; and &gt;

**Comment by rtfb** [comment]
After some poking around, it looks like this can't work, as per markdown [spec](https://daringfireball.net/projects/markdown/syntax#html):

> Note that Markdown formatting syntax is not processed within block-level HTML tags. E.g., you can’t use Markdown-style *emphasis* inside an HTML block.

So even if we whitelisted `<html>`, all the document would be treated as block-level HTML segment and none of included markdown would get parsed.

I suggest splitting the document into HTML and markdown bits, processing the latter with Blackfriday and then joining everything back together.

**Comment by crispgm** [comment]
Thanks guy. I got it. 

However, other typical markdown parser do support this cuz there is not an official standard for markdown.
