### ISSUE TITLE
Line break with a backslash before the line ending

### ISSUE THREAD

**Issue by heavywatal** [russross/blackfriday#245]
Trailing spaces can be invisible and truncated automatically by an editor. Adding explicit `<br>` tags is fine, but it makes a source file a little ugly. It would be nice if we can insert a line break with a short and visible code, `\`. This behavior is compatible with [the tentative CommonMark spec](http://spec.commonmark.org/0.24/#hard-line-breaks).

**Comment by shurcooL** [comment]
I have a question. If `\` means `<br>`, how would you write a literal `\` at the end of a line? Two `\\` or something else?

**Comment by rtfb** [comment]
There is an `EXTENSION_BACKSLASH_LINE_BREAK` and it's included in the default extension set. Is this what you're looking for, @heavywatal?

**Comment by heavywatal** [comment]
Yes, a backslash-escaped backslash `\\` seems reasonable. I admit that it can be confusing because `\\` is often used as a line break in LaTeX math equations.

Thank you, @rtfb! Yes, it is. I have no idea why I missed that option.
