### ISSUE TITLE
internal error: (*Html).ensureUniqueHeaderID autotmp_734 (type *int) recorded as live on entry, p.Pc=15325

### ISSUE THREAD

**Issue by gyuho** [russross/blackfriday#251]
One of our dependecy (https://github.com/spf13/cobra) imports `blackfriday` and we have Travis CI running on Go tip. And we got this error:

```
gopath/src/github.com/coreos/etcd/vendor/github.com/russross/blackfriday/html.go:932: internal error: (*Html).ensureUniqueHeaderID autotmp_734 (type *int) recorded as live on entry, p.Pc=15325
```

- https://travis-ci.org/coreos/etcd/jobs/120195611
- https://github.com/coreos/etcd/blob/master/vendor/github.com/russross/blackfriday/html.go#L932-L949

It seems related to Golang [GC](https://github.com/golang/go/issues/13264).

Has anyone seen this error before? I would like to ask here first before I file this to upstream.

Thanks!

**Comment by shurcooL** [comment]
I've seen it on Go tip (but not Go 1.6) quite consistently in the last few weeks in CI as well.

E.g., see https://travis-ci.org/shurcooL/markdownfmt/jobs/120019027.

**Comment by gyuho** [comment]
@shurcooL Thanks. I got it reproduced. Seems only happens with `-race` flag. Will file an issue to Golang.

**Comment by gyuho** [comment]
Fixed via https://github.com/golang/go/issues/15091. Thanks!
