### ISSUE TITLE
Convert YAML front matter to tables

### ISSUE THREAD

**Issue by rnarian** [russross/blackfriday#254]
I created [this issue](https://github.com/gogits/gogs/issues/2931) in [gogits/gogs](https://github.com/gogits/gogs) and they pointed me here. It would be great if YAML front matter could be converted to tables.

#### Examples

Gogs:

> ![bildschirmfoto 2016-04-05 um 18 28 20](https://cloud.githubusercontent.com/assets/1174951/14289703/46bd7010-fb5c-11e5-97c9-2af36a23a937.png)
> (https://try.gogs.io/rnarian/yaml-frontmatter/src/master/test.md)

Github:

> ![bildschirmfoto 2016-04-05 um 18 28 38](https://cloud.githubusercontent.com/assets/1174951/14289728/5ac0495c-fb5c-11e5-9aed-bf9837a8b33e.png)
> (https://github.com/rnarian/yaml-frontmatter/blob/master/test.md)

**Comment by shurcooL** [comment]
This seems out of scope for `blackfriday`. It's a Markdown processor, not a YAML front matter processor:

> Blackfriday is a [Markdown][http://daringfireball.net/projects/markdown/] processor implemented in [Go][http://golang.org/].

That doesn't mean this shouldn't be done, I just think it should be done by some higher level package that uses `blackfriday` and something else to deal with a (possible) YAML header.

What are your thoughts on that?

**Comment by rnarian** [comment]
Ok I see. I'm not actually involved in the development of gogs. I just figured I'd post it here as the developers directed me to blackfriday. I definitely see your point.

**Comment by korimas** [comment]
> This seems out of scope for . It's a Markdown processor, not a YAML front matter processor:`blackfriday`
> 
> > Blackfriday is a [Markdown](http://daringfireball.net/projects/markdown/) processor implemented in [Go](http://golang.org/).
> 
> http://daringfireball.net/projects/markdown/ does not mention anything about YAML as far as I know.
> 
> That doesn't mean this shouldn't be done, I just think it should be done by some higher level package that uses and something else to deal with a (possible) YAML header.`blackfriday`
> 
> What are your thoughts on that?

I approve of you that `blackfriday` is a Markdown processor and it should not parse yaml，But it would be better if `blackfriday` can identify the content of the front matter. like `Typora`,

In `Typora`, The content:
```
---
title: Titlexxx
date: 2020-02-21 14:40:19
permalink: /pages/a1bc87
categories:
  - xxx
  - yyy
---



# Title 

content
```
displayed like:

![image](https://user-images.githubusercontent.com/15672287/103252409-b46fca00-49b7-11eb-89dd-6dda40a55b3f.png)

So, no need to convert them to tables, only display correctly
