### ISSUE TITLE
Adding <p class=".."> to support paragraph indenting similar to TeX

### ISSUE THREAD

**Issue by adrianmsmith** [russross/blackfriday#260]
I would like to achieve the following indenting effect for paragraphs, similar to the style that TeX uses.

```
This is the first paragraph, it's not indented.
   This is another paragraph, it's indented

* A bullet
* Another bullet

This is another paragraph, it's not indented, as it's preceded by
something other than a paragraph.
   This is another paragraph, it's indented.
```

I would like to achieve the effect that paragraphs in general are indented, but the first paragraphs, and paragraphs after non-paragraphs, are not. 

This cannot be achieved using plain CSS and HTML without Javascript, if the HTML just uses a plain `<p>` tag. It's necessary to add classes to indicate if the paragraph is the first or not. The names that the TeX outputter uses for these classes are `<p class="pFirst">` and `<p class="pNext">`; these names seem good enough to me.

I would like to extend blackfriday with the facility to always output these classes with paragraph tags. Having extra class attributes in paragraph tags should not cause any problem to anyone who is not interested in this styling, so I would not add the complexity to turn their output on/off with a parameter.

I would be happy to do the work to program this. Would you be interested in such a patch?

**Comment by rtfb** [comment]
At the first glance this behavior seems to be rather specific and begs to be implemented as a kind of middleware outside of the library.

Would you be interested to try out the v2 of Blackfriday? Check it out in the `v2` branch. You can import it as `gopkg.in/russross/blackfriday.v2`. The new version exposes full abstract syntax tree of the parsed document, so you can walk the tree, overriding only those nodes that interest you, while rendering the remaining nodes with the default renderer. A simple example can be found here: https://gist.github.com/rtfb/08babeb67d37514f5322722797a6bd6a

**Comment by adrianmsmith** [comment]
I can absolutely see your point of view. I wasn't sure if it belonged in blackfriday myself.

The reasons I thought it might belong there, as opposed to client code using blackfriday:

* Having indented paragraphs is a standard style, e.g. for books. So I could imagine there are others out there who might want it. Although I admit, it might be a standard style in the print world, but it's very unusual on the web.

* TeX does it that way when producing HTML. Although, of course, that by no means implies that every system should produce HTML like that, it does at least show there is precedent for this approach.

* It would not harm those who do not wish to use the feature, as it is unlikely they have CSS classes with these names defined, so the extra CSS classes in the paragraph tag would be ignored.

* Obviously every change increases code complexity, which is bad. Nevertheless, it would not increase code and test complexity by much.

I leave the decision to you, of course, if you want this feature in your code or not.

Thanks for your suggestion about v2. Currently I am creating sites with hugo, which doesn't use v2 (as far as I can tell). However, I believe I can override the methods like `Paragraph` there, to achieve the effect I want, let's see...

**Comment by adrianmsmith** [comment]
It has come to my attention that I can achieve what i want by using [CSS sibling selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/Adjacent_sibling_selectors) which I had not heard of before. So no change of the `<p>` tag is necessary to achieve this effect.
