### ISSUE TITLE
Definition lists containing other lists are broken

### ISSUE THREAD

**Issue by moorereason** [russross/blackfriday#263]
PR #261 broke definition lists that contain other lists.  See the comments by @miekg on that PR.

Example test:

```
diff --git a/block_test.go b/block_test.go
index bb3a50b..f3618fe 100644
--- a/block_test.go
+++ b/block_test.go
@@ -960,6 +960,14 @@ func TestDefinitionList(t *testing.T) {
                        "<dd><p>Definition b</p></dd>\n" +
                        "</dl>\n" +
                        "\n<p>Text 2</p>\n",
+
+               "Term 1\n:   Definition a\n\n    Text 1\n\n    1. First\n    2. Second",
+               "<dl>\n" +
+                       "<dt>Term 1</dt>\n" +
+                       "<dd><p>Definition a</p>\n\n" +
+                       "<p>Text 1</p>\n\n" +
+                       "<ol>\n<li>First</li>\n<li>Second</li>\n</ol></dd>\n" +
+                       "</dl>\n",
        }
        doTestsBlock(t, tests, EXTENSION_DEFINITION_LISTS)
 }
```

**Comment by rtfb** [comment]
Reopening this as per @moorereason's comment on #264 that it only solves half of the problem.

**Comment by miekg** [comment]
I also have problems with a definition list containing a definition list:
~~~
Item1
: Def1

    aThe
    : a

    bThe
    : b

    cThe
    : c
~~~
compiles to
~~~
% ./blackfriday-tool ../../miekg/mmark/test.md
<dl>
<dt>Item1</dt>
<dd><p>Def1</p>

<p>aThe</p>

<dl>
<dd>a</dd>
<dt>bThe</dt>
<dd>b</dd>
<dt>cThe</dt>
<dd>c</dd>
</dl></dd>
</dl>
~~~
I.e. the first term is considered part of upper element and not considered a new list

**Comment by mmalone** [comment]
It's been a while, any update on this? I'm having trouble with nested definition lists. Happy to work on a fix but wanted to check whether there's an existing fix laying around somewhere first. I'm working with v2.

**Comment by miekg** [comment]
Its' related to the `if indent <= itemIndent {` check. The v2 branch checks if the type of list has *changed* (`p.listTypeChanged`) so it still doesn't detect this same list in list. I wonder if that check should be simpler.

**Comment by moorereason** [comment]
Since blackfriday appears to be abandoned, I'm doing the same with this issue.
