### ISSUE TITLE
How do I stylize the markdown code?

### ISSUE THREAD

**Issue by xDinomode** [russross/blackfriday#268]
Is there a default sylesheet I can use to stylize the outputed \<pre>\<code>\</code>\</pre> that blackfriday creates?

**Comment by shurcooL** [comment]
> Is there a default sylesheet I can use

I don't believe `blackfriday` itself provides any default CSS to use; it's something one usually creates or finds from another source.

Perhaps someone else can offer another suggestion.

**Comment by Depado** [comment]
Hi there,
I'm currently using http://prismjs.com/ to highlight the code blocks (if that's what you need ?)
Works pretty fine and doesn't need tweaking on the Blackfriday's side :)
