### ISSUE TITLE
LaTeX output is stubbed for EXTENSION_FOOTNOTES

### ISSUE THREAD

**Issue by rtfb** [russross/blackfriday#28]

**Comment by Ambrevar** [comment]
Done: https://bitbucket.org/ambrevar/blackfriday-latex

**Comment by shurcooL** [comment]
I see https://bitbucket.org/ambrevar/blackfriday-latex is already mentioned in the v2 README. Anything else to do there, or shall we close this?

**Comment by Ambrevar** [comment]
We can close it.
