### ISSUE TITLE
document v2 installation

### ISSUE THREAD

**Issue by jmhodges** [russross/blackfriday#292]
The default README doesn't mention the v2 branch nor if it's considered stable (is it?) which means folks looking for the latest code don't know where to get it unless they're trawling through the issues.

It seems that, at least for new contributors, the master README should maybe get an update?

Not sure what the plans are so I made this ticket instead of sending a PR.

**Comment by rtfb** [comment]
It's considered functionally complete, but API-wise it's not yet stable, so I was pushing back the announcement. But I guess it's time, with a note of caution about potential breaking changes. I'll write something up in upcoming days. Thanks for bringing this up!

**Comment by shurcooL** [comment]
> But I guess it's time, with a note of caution about potential breaking changes.

What about your comment in https://github.com/russross/blackfriday/pull/286#issue-168358780:

> Currently v2 is ~2.7x slower than v1.

Has that changed since then to not be a blocking issue?

**Comment by rtfb** [comment]
As of current v2 tip code, it is still considerably slower than v1 (none of my performance optimizations have been pushed yet). But I never considered that to be a blocking issue -- v2 is a complete overhaul, so I see a change in performance characteristics as a part of a picture. Definitely a part significant enough to mention in docs, though, so thanks for bringing it up.

**Comment by shurcooL** [comment]
Hmm, I'm slightly concerned that if it's still considerably slower (i.e., more than 1.5x slower), then announcing it at this stage may make a lot more people dismiss it as "ehh, it's slower, I'll wait a year and maybe switch to it then" and then forget about it. When we do the perf optimizations that may make it as fast, if not faster than v1, it'll be hard to re-announce it.

If the perf optimizations (that you already have in mind, for example) are not going to take a significant time, why not hold off announcing v2 until it's a bit faster?

It'll be hard to get people to switch from v1 to v2 unless they're writing new projects anyway, but lower performance may make them reconsider.

Of course, I trust you have a better sense of what's the best of action plan, I just wanted to share this comment.

**Comment by Ambrevar** [comment]
Well, as @rtfb said, v2 does more than v1, so a performance cost is to be expected. As such benchmarking v1 vs. v2 has limited relevance.
When releasing v2, it makes sense to emphasize on the _new renderer interface_ rather than the performance loss.

That being said, I agree that we should run v2 through a good profiling session before release.
I haven't reviewed the whole code, but while contributing I have spotted some wasted cycles here and there.

**Comment by rtfb** [comment]
Oh, good that you brought it back, I forgot to announce that I have recently pushed a branch, `v2-perf-tweaks`, with several low hanging fruits reaped. It gains almost 2x cpu speedup and cuts allocations more than in half. I will open a separate discussion thread for its discussion prior to PR.
