### ISSUE TITLE
Exposing the parser via dependency injection

### ISSUE THREAD

**Issue by jamesjia94** [russross/blackfriday#320]
Maybe this will change in v2, but for the time being is it possible to allow people to create a custom parser by exposing the parser struct and passing the parser as a parameter [here](https://github.com/russross/blackfriday/blob/master/markdown.go#L345)?

I have a use case where I want to support only a subset of markdown, but using a custom renderer isn't good enough. For example, I don't want to support horizontal rules, but the renderer isn't passed in the original markdown [here]( https://github.com/russross/blackfriday/blob/master/block.go#L119).

**Comment by shurcooL** [comment]
> Maybe this will change in v2

Yes, I'm pretty sure it has already changed in v2. You should take a look at it.

**Comment by jamesjia94** [comment]
I'd prefer to use v1 as it looks like v2 is still in flux (please correct me if I'm wrong).

**Comment by shurcooL** [comment]
v2 is still in development but is ready for early usage and receiving feedback.

v1 is stable and mature, but not under active development, only bug fixes and minor changes.
