### ISSUE TITLE
v2: Why are we using the word "header" instead of "heading"?

### ISSUE THREAD

**Issue by shurcooL** [russross/blackfriday#330]
As part of v2, we made many breaking API changes and fixed long standing issues, like not following idiomatic Go names for identifiers. Since v2 isn't fully released yet, I thought this potential issue is not too late to report. We may or may not want to consider fixing it as well, if it's a real issue.

I just realized that the \<h1\> through \<h6\> tags stand for "heading", not "header". So why we does blackfriday seem to refer to it as "header" everywhere?

See https://github.com/shurcooL/github_flavored_markdown/pull/10 for additional details and motivation. I'll paste relevant parts here:

> Heading seems like a more appropriate name, given that elements \<h1\> through \<h6\> stand for "heading" (see HTMLHeadingElement), not "header" (as I originally mistakenly thought). There is a \<header\> element in HTML5, but that's usually a higher level container that contains a few headings and a paragraph.
>
> This func returns a \<h1\>-\<h6\> element. Based on that, heading seems like a more appropriate name.
>
> > The HTML \<h1\>–\<h6\> elements represent six levels of section headings.
> > \<h1\> is the highest section level and \<h6\> is the lowest.
>
> > The HTML \<header\> element represents a group of introductory or
> > navigational aids. It may contain some heading elements but also other
> > elements like a logo, a search form, and so on.
>
> Sources:
>
> -	https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements
> -	https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header

For example, consider `headerTagsFromLevel`:

```Go
func headerTagsFromLevel(level int) ([]byte, []byte) {
	switch level {
	case 1:
		return h1Tag, h1CloseTag
	case 2:
		return h2Tag, h2CloseTag
	case 3:
		return h3Tag, h3CloseTag
	case 4:
		return h4Tag, h4CloseTag
	case 5:
		return h5Tag, h5CloseTag
	default:
		return h6Tag, h6CloseTag
	}
}
```

This func is clearly incorrectly named "headerTags" given what it does, which is return \<h1\> and \</h1\> heading tags.

/cc @rtfb

Two questions:

1. Is this an issue (albeit minor) or not an issue (i.e., maybe there's a mistake in my logic or understanding)?
2. If it is an issue, is it worth fixing?

Doing a quick grep on https://gotools.org/github.com/russross/blackfriday?rev=v2, I see we have 106 instances of "header", and only 1 instance of "heading". Header is used in many places as part of the API.

**Comment by rtfb** [comment]
You're absolutely right, we should respect HTML (and, well, English) terminology and use "heading". And since there are a few points in public interface, now is the right time to fix them. Do you want to do it yourself or should I go and clean this up?

**Comment by shurcooL** [comment]
Great! Glad to hear we can make v2 even better.

If it's convenient for you and you don't mind doing it, that works for me. Otherwise, I can happily do this too.

**Comment by rtfb** [comment]
I'll try to do it right away. Oh, and as to the "why?", the answer seems to be the [spec](https://daringfireball.net/projects/markdown/syntax): it's using "header".

**Comment by shurcooL** [comment]
Oh, that's very interesting and definitely explains it. I wonder what the thinking there was...

**Comment by shurcooL** [comment]
Some redeeming evidence to support this issue is the fact that CommonMark spec refers to them as "headings" too, not headers.

http://commonmark.org/help/
http://spec.commonmark.org/0.26/#atx-headings
http://spec.commonmark.org/0.26/#setext-headings

**Comment by shurcooL** [comment]
Got a reply from John Gruber that confirms the issue is valid! 🎉

> I never thought about it before. It should be “headings”.

Source: https://twitter.com/gruber/status/831256372968824834.
