### ISSUE TITLE
Footnote markup has obsolete rel="footnote" attribute value

### ISSUE THREAD

**Issue by jturner314** [russross/blackfriday#336]
The footnote markup does not pass HTML validation (https://validator.w3.org/nu/) because `footnote` is not a valid value for the `rel` attribute. See:

* [A similar issue in Redcarpet](https://github.com/vmg/redcarpet/issues/536)
* [A list of all valid `rel` values, which does not include `footnote` (WHATWG)](https://html.spec.whatwg.org/multipage/semantics.html#linkTypes)
* [A list of obsolete `rel` values, including `footnote` (Microformats)](http://microformats.org/wiki/existing-rel-values#dropped)
* [The W3C recommendation for footnotes, which recommends just using an `a` element without `rel`](https://www.w3.org/TR/html5/common-idioms.html#footnotes)

Ideally, the `rel` attribute would be removed from footnote links.

**Comment by kaushalmodi** [comment]
Bump, anyone?
