### ISSUE TITLE
bullet list is not rendered

### ISSUE THREAD

**Issue by golang101** [russross/blackfriday#339]
(Tested on v2.)

This will be rendered as bullet list

	Index

	* aaaa
	* aaaa

but this will not 

	Index
	* aaaa
	* aaaa

For the first rendered one, there is a large margin between the "index" line and the bullet list.
This is why I want to use the second one to remove the margin.

btw, github pages and visual studio code both render the second one as bullet lists. But there are still large margins between the "index" line and the bullet list (same output as the first one by blackfriday). 

As html standard doesn't allow bullet list to appear in p block, I think it would be cool to render the second one as 

	<div>Index
	<ul>
	<li>aaaa</li>
	<li>aaaa</li>
	</ul>
	</div>
	<p></p>

**Comment by shurcooL** [comment]
Did you use `EXTENSION_NO_EMPTY_LINE_BEFORE_BLOCK` extension?

```go
const (
	...
	EXTENSION_NO_EMPTY_LINE_BEFORE_BLOCK // No need to insert an empty line to start a (code, quote, ordered list, unordered list) block
	...
)

**Comment by golang101** [comment]
Yes, v1 EXTENSION_NO_EMPTY_LINE_BEFORE_BLOCK works.
btw, what's the equivalent in v2?

**Comment by rtfb** [comment]
That would be `NoEmptyLineBeforeBlock`.

**Comment by golang101** [comment]
yes, it works in v2.

btw, is there a way to remove the margin between the "Index" line and the bullet list?

**Comment by rtfb** [comment]
> btw, is there a way to remove the margin between the "Index" line and the bullet list?

I guess the best way to do that would be CSS, if I read your question correctly.

**Comment by golang101** [comment]
ok. Thanks.
