### ISSUE TITLE
Markdown Renderer to facilitate transforms

### ISSUE THREAD

**Issue by jonasfj** [russross/blackfriday#349]
A markdown renderer that renders markdown to markdown would be awesome for transforming markdown...

Example: Increase headline levels by one, so you can wrap it in another layer.. or just ensure that markdown formatting is consistent, like gofmt...

Embedding and overwriting specific methods would also be useful...I can also imagine it as useful for learning how to write renderer implementations.

Anyways, this project has a great structure, well suited for doing markdown to markdown transforms.. so a renderer making that easy would be cool :)

**Comment by shurcooL** [comment]
Take a look at v2 API, it improves the `Renderer` interface significantly, making it much easier to implement custom renderers.

> or just ensure that markdown formatting is consistent, like gofmt...

This already exists, see `markdownfmt` renderer at https://github.com/russross/blackfriday#other-renderers for example.

**Comment by jonasfj** [comment]
wow, thanks...
