### ISSUE TITLE
Help getting markdown table working

### ISSUE THREAD

**Issue by dadatawajue** [russross/blackfriday#351]
Hi, I'm trying to figure out how to use this library but it does not seem to be working, not sure if I'm doing something wrong.. This is the input I feed using a HTML textarea:
```
FINALS:
| Match URL | PlayerX |   | Player Y |
| - | - | - | - |
| [Match 1](someurl.com) | foo | vs | bar |
| [Match 2](someurl.com) | foo | vs | bar |
| [Match 3](someurl.com) | foo | vs | bar |
------
SEMI-FINALS:
| Match URL | PlayerX |   | Player Y |
| - | - | - | - |
| [Match 1](someurl.com) | foo | vs | baz |
| [Match 2](someurl.com) | foo | vs | baz |
| [Match 3](someurl.com) | foo | vs | baz |
```

Then in Go I get and print it like this:

```
unsafe := blackfriday.MarkdownCommon([]byte(r.FormValue("content")))
mdContent := bluemonday.UGCPolicy().SanitizeBytes(unsafe)
log.Println(string(mdContent))
```

But the result mysteriously ends up like this rather than a table:

```
<p>FINALS:
| Match URL | PlayerX |   | Player Y |
| - | - | - | - |
| <a href="someurl.com" rel="nofollow">Match 1</a> | foo | vs | bar |
| <a href="someurl.com" rel="nofollow">Match 2</a> | foo | vs | bar |
| <a href="someurl.com" rel="nofollow">Match 3</a> | foo | vs | bar |

<hr/>

<p>SEMI-FINALS:
| Match URL | PlayerX |   | Player Y |
| - | - | - | - |
| <a href="someurl.com" rel="nofollow">Match 1</a> | foo | vs | baz |
| <a href="someurl.com" rel="nofollow">Match 2</a> | foo | vs | baz |
| <a href="someurl.com" rel="nofollow">Match 3</a> | foo | vs | baz |</p>
```

**Comment by shurcooL** [comment]
From https://help.github.com/articles/organizing-information-with-tables/:

> There must be at least three hyphens in each column of the header row.

Try this:

    | Match URL | PlayerX |   | Player Y |
    | --- | --- | --- | --- |
    | [Match 1](someurl.com) | foo | vs | bar |
    | [Match 2](someurl.com) | foo | vs | bar |
    | [Match 3](someurl.com) | foo | vs | bar |

**Comment by dadatawajue** [comment]
Oh, that works.. seems I also had to create an extra newline between 'FINALS' and the table. Thanks a lot :)
