### ISSUE TITLE
Question about EXTENSION_HARD_LINE_BREAK

### ISSUE THREAD

**Issue by hwsoderlund** [russross/blackfriday#355]
Hi, I have a question about the use of the extension flag EXTENSION_HARD_LINE_BREAK:

I am hoping to use blackfriday to implement basic markdown support for non-technical users in a  communication platform. The main purpose for now is to simply make pasted links clickable while preserving line breaks. I was hoping to avoid having to teach our users the rules of markdown and simply allow them to freely write text and then converting to markdown behind the scenes. But I am having trouble achieving line breaks within paragraphs, without requiring the double spaces. 

Here is an example of what I am trying to do. Note that in the following input text, there are no double spaces after `Here is a link for you:` and `Best regards,`
```
Hello Jim,

Here is a link for you:
https://example.com

Best regards,
/Anna
```

Here is the output I was hoping to achieve (formatted for readability):
```
<p>Hello Jim,</p>
<p>
  Here is a link for you:
  <br>
  <a href="https://example.com">https://example.com</a>
</p>
<p>
  Best regards,
  <br>
  /Anna
</p>
```

I have tried using EXTENSION_HARD_LINE_BREAK, but it does not seem to do what I want. Double spaces are still required to get the desired line breaks. Is there a way to do what I want, or am I misinterpreting how this extension works?

**Comment by shurcooL** [comment]
> I have tried using EXTENSION_HARD_LINE_BREAK, but it does not seem to do what I want.

Did you test with latest version of blackfriday? Can you post the code?

Your understanding of EXTENSION_HARD_LINE_BREAK is correct, it should do what you want. In my testing, it does exactly that. For the input you provided, here's my output without EXTENSION_HARD_LINE_BREAK:

```HTML
<p>Hello Jim,</p>

<p>Here is a link for you:
https://example.com</p>

<p>Best regards,
/Anna</p>
```

And here's with EXTENSION_HARD_LINE_BREAK:

```HTML
<p>Hello Jim,</p>

<p>Here is a link for you:<br>
https://example.com</p>

<p>Best regards,<br>
/Anna</p>
```

The code I tested with is [here](https://play.golang.org/p/l8y88DsVAb).

**Comment by hwsoderlund** [comment]
Thank you. Your example works exactly as expected. My own test code was a bit more elaborate, attempting to replicate the MarkdownCommonMethod, but with the addition of EXTENSION_HARD_LINE_BREAK. I can only assume I must have gone wrong somewhere. Please consider this issue solved. 

FYI, I am using the latest master.
