### ISSUE TITLE
Setting for target=_blank for external links only

### ISSUE THREAD

**Issue by arikroc** [russross/blackfriday#361]
This would be useful

Using with hugo

**Comment by shurcooL** [comment]
`bluemonday` already supports this, as part of its sanitization process.

Look into its `AddTargetBlankToFullyQualifiedLinks` option, described at https://github.com/microcosm-cc/bluemonday#links.

**Comment by arikroc** [comment]
For anyone else looking at doing this for use to set target=_blank for external links in Hugo, see here: https://discuss.gohugo.io/t/external-links-in-new-tab/5311/3
