### ISSUE TITLE
Footnotes and references that are used more than once creates duplicate footnotes

### ISSUE THREAD

**Issue by arikroc** [russross/blackfriday#362]
Is there a hidden setting to change this?

**Comment by arikroc** [comment]
Is this likely to be changed?

**Comment by arikroc** [comment]
See also: https://github.com/russross/blackfriday/issues/241

**Comment by shurcooL** [comment]
If this is the same as #241, let's close this to avoid having an extra duplicate issue, and continue discussion there.

**Comment by arikroc** [comment]
Closed this one. What do you think regarding #241 ?
