### ISSUE TITLE
how to escape \\

### ISSUE THREAD

**Issue by tpapp** [russross/blackfriday#363]
(note: I [asked this](https://discuss.gohugo.io/t/how-to-get-a-from-markdown/6691) on the Hugo discussion forum, didn't get a reply, asking here as AFAIK this is the backend used by Hugo).

When I write 
```md
\\
```
in Markdown it is replaced by
```html
<br />
```
in the generated HTML output.

How should I escape `\\` so that it is left alone? I need it for `multline` in MathJax. I tried `\\\\` but that gives `\<br />` instead in the HTML output.

**Comment by shurcooL** [comment]
I think this depends on the exact configuration of blackfriday and any sanitization being done.

I tested blackfriday at https://dmitri.shuralyov.com/projects/live-markdown/live-markdown.html, and for me, doing `\\` escapes to `\` as expected:

![image](https://cloud.githubusercontent.com/assets/1924134/26417728/03f32afa-4088-11e7-8bbc-c2606a32a49b.png)

**Comment by rtfb** [comment]
I think you misunderstood the question, @shurcooL. Looks like the question is how one can produce two consecutive backslashes in the output. Is that right, @tpapp?

Unfortunately, I can't answer that right away, need to dig into code to see what exactly is going on.

**Comment by tpapp** [comment]
@rtfb: indeed, that is the issue. However, using the link above provided by @shurcooL , `\\\\` renders into `\\`. Should I open an issue for Hugo then?

**Comment by shurcooL** [comment]
> how one can produce two consecutive backslashes in the output

It's no different than producing a single backslash. Just repeat the escaped backslash twice.

**Comment by tpapp** [comment]
It looks like Hugo has `EXTENSION_BACKSLASH_LINE_BREAK` [enabled](https://github.com/spf13/hugo/blob/e98f885b8af27f5473a89d31d0b1f02e61e8a5ec/helpers/content.go#L267), which was causing this problem for me. Disabling it makes everything work fine.

Thank you very much for your help, I am closing the issue as this is not a problem with Blackfriday.

**Comment by lizyn** [comment]
> It looks like Hugo has EXTENSION_BACKSLASH_LINE_BREAK enabled, which was causing this problem for me. Disabling it makes everything work fine.

@tpapp May I ask how to do this? I checked the [hugo doc](https://gohugo.io/getting-started/configuration/#blackfriday-extensions) but am still confused.

**Comment by lizyn** [comment]
Sorry to bother you. I have figured out there's an error in the doc where `extensionsmask` should be "to disable extensions" rather than "to enable".
