### ISSUE TITLE
reference links not working properly

### ISSUE THREAD

**Issue by scrumit** [russross/blackfriday#374]
I'm using Algernon, which uses blackfriday for markdown rendering.

I added a second place on a page with the same link, so changed it to a reference link:

```
[ROWeb]:(http://algernon.roboticoverlords.org/)
```

And what Algernon (blackfriday) parsed that to was:

```
/Users/buildslave/Library/Containers/org.roboticoverlords.algernon/Data/Documents/Algernon/(http:/algernon.roboticoverlords.org/)
```

**Comment by dolanor** [comment]
I have the same problem on gogs (which also uses blackfriday I think)

The link to the reference-link spec: https://daringfireball.net/projects/markdown/syntax#link

**Comment by rtfb** [comment]
The parentheses around the URL not needed and they mislead the parser into thinking that it's a local URL. `[ROWeb]: http://algernon.roboticoverlords.org/` should work well.

Closing this.

**Comment by dolanor** [comment]
wow, thanks @rtfb for investigating. I guess I totally misread.
In fact, when doing as the spec says, it works. I guess I put the `()` overreading…

**Comment by scrumit** [comment]
Yes, I submitted here and to Algernon, where it was also closed.

My bad, not reading the markdown spec properly. Sorry.
