### ISSUE TITLE
Add spaces to angle quotes for French guillemets

### ISSUE THREAD

**Issue by aurelberra** [russross/blackfriday#378]
In 2014 support was added for angle quotes in BlackFriday thanks to @bep (#128). However, the French [guillemets](https://en.wikipedia.org/wiki/Guillemet) would also require non-breaking spaces: "this" should not become «that», but « that ».

Such further enhancement would make a great difference for French users, as mentioned in [Hugo issue #3725](https://github.com/gohugoio/hugo/issues/3725).

**Comment by bep** [comment]
I can take a stab on this when I get some spare time, should not be to hard; but looking at this:

https://en.wikipedia.org/wiki/Guillemet

I guess we should add an option that should work for both "regular" and angled quotes, i.e. for gullimets in general.

**Comment by aurelberra** [comment]
Do you mean enabling “quotes”, «double angle quotes» and «&nbsp;guillemets&nbsp;» (with `&nbsp;`) as options, the first one being the default? That would be really nice and would cover most needs! I'm happy to test if I can be of any help.

Adding British-style ‘quotes’ would make the list complete, I think – cf. for instance LaTeX [`csquotes`](http://ctan.sharelatex.com/tex-archive/macros/latex/contrib/csquotes/) package, which also deals with second-level quotes, but we probably don't need such sophistication here.

**Comment by bep** [comment]
Currently we have:

* `HTML_USE_SMARTYPANTS`=> regular quotes (I call them that ...)

If you add 

* `HTML_SMARTYPANTS_ANGLED_QUOTES` => Angled quotes (which fits the French norm)

If we add a new option:

* `HTML_SMARTYPANTS_QUOTES_NBSP`

Which, in both cases above, will insert `&nbsp;`.

**Comment by aurelberra** [comment]
Ok, so you would combine two `smartypants` options. It seems fine, but I don't see how you could need `&nbsp;` with the "regular", US quotes: what would be the “&nbsp;use case&nbsp;”?

**Comment by bep** [comment]
>what would be the “ use case ”?

I didn't know about the French use case, either -- but I don't care too much about the usefulness, it just makes sense and is the simplest way to add this.

**Comment by aurelberra** [comment]
It has its own logic. If it's easier than adding an option like `HTML_SMARTYPANTS_ANGLED_QUOTES_NBSP`, then by all means!

**Comment by rtfb** [comment]
Wow, this baffles me a bit. Are you saying that there are cases in French when people write quoted text with extra spaces around it inside Guillemets?

**Comment by aurelberra** [comment]
Yes, this is the norm: «&nbsp;TEXT&nbsp;» (though these are thin spaces in good typography).

**Comment by bep** [comment]
It baffles me as well, but it is documented in the Wikipedia article linked above:

https://en.wikipedia.org/wiki/Guillemet

**Comment by rtfb** [comment]
> Yes, this is the norm: « TEXT » (though these are thin spaces in good typography).

Damn, natural languages are _weird_ :-)

> documented in the Wikipedia article linked above:

Yeah, I missed that needle in the hay of information.
