### ISSUE TITLE
Blackfriday-LaTeX moved to GitHub

### ISSUE THREAD

**Issue by Ambrevar** [russross/blackfriday#388]
Could you update the link in the README?
https://github.com/Ambrevar/Blackfriday-LaTeX

Thanks!

**Comment by shurcooL** [comment]
Resolved by #389 (not closed automatically because v2 isn't default branch of this repo).

**Comment by tobydriscoll** [comment]
For me a (dead) bitbucket link comes up. Anyhow, the repo seems to have moved again, to `https://gitlab.com/ambrevar/blackfriday-latex`.

**Comment by nschonni** [comment]
Looks like there is a PR for it over #465
