### ISSUE TITLE
Code block with semicolon, v2

### ISSUE THREAD

**Issue by jelinden** [russross/blackfriday#399]
If I add a semicolon (;) anywhere in a code block (in this case between the braces), it brakes the rendering totally.
`<p>code() {</p>`
should be
<pre><code>code() {
;
}</code></pre>

**Comment by shurcooL** [comment]
You included "v2" in the issue title, did you mean this bug applies to blackfriday v2 only?

**Comment by jelinden** [comment]
I'm using v2. Maybe I should try v1 if it works there.

**Comment by jelinden** [comment]
My mistake, it works. Encoding issue, should have confirmed with a test.
