### ISSUE TITLE
deck renderer

### ISSUE THREAD

**Issue by ajstarks** [russross/blackfriday#40]
I've written a renderer for deck markup [1] [2] [3] [4] and I have a couple of questions:

1) is it possible to add a flag so that the list renderer can distinguish between a list beginning with '-' and from one beginning with '_'?  I want to render the '-' with without bullets, and the '_' with bullets.
For example:

```
  - item 1
  - item 2
```

should generate

```
  <list xp="10" yp="90" sp="2">
      <li>item 1</li>
      <li>item 2</li>
  </list>
```

but

```
  * item 1
  * item 2
```

generates:

```
 <list xp="10" yp="90" sp="2" type="bullet">
      <li>item 1</li>
      <li>item 2</li>
  </list>
```

2) The image parser places paragraph tags around an image. Is there a way to just get the plain image? For example:

```
   ![50,50,960,540](/Users/ajstarks/Images/desert960.jpg "The desert")
```

I'd like to render in deck without as:

```
<image name="/Users/ajstarks/Images/desert960.jpg" xp="50" yp="50" width="960" height="540" caption="The desert" />
```

Finally, I've updated blackdown-tool to use a -format flag so that you can say:

$ blackdown-tool -format html ...
$ blackdown-tool -format latex ...
$ blackdown-tool -format deck ...

[1] https://github.com/ajstarks/deck
[2] http://godoc.org/github.com/ajstarks/deck
[3] https://github.com/ajstarks/deck/blob/master/examples/deck.xml
[4] https://github.com/ajstarks/deck/blob/master/examples/deck.pdf?raw=true

**Comment by rtfb** [comment]
Hey @ajstarks, not sure if the answer is still relevant after four years, but with v2, you can do both these things.
