### ISSUE TITLE
Convert HTML to markdown

### ISSUE THREAD

**Issue by gadelkareem** [russross/blackfriday#429]
Any possibility to convert HTML to markdown?

**Comment by shurcooL** [comment]
In a general case, it’d be very hard and probably impossible.

For a specific subset of features and well defined restrictions on input, you should be able to create something for your task.

I’ve done something like this in the past, if you want an example, see https://github.com/shurcooL/go/commit/018af570ed6145a402f80690b0c23ba48bbca332.

**Comment by gadelkareem** [comment]
I found https://github.com/lunny/html2md but it depends heavily on regex which is very slow. I thought blackfriday would easily reverse the parser even for basic formatting and leave the rest as text.

**Comment by shurcooL** [comment]
Blackfriday includes a Markdown parser and HTML renderer. It does not include an HTML parser.

**Comment by gadelkareem** [comment]
I think it is easy to implement specially with something like https://github.com/PuerkitoBio/goquery 
You can keep this as a feature request or close it if there is no plan for it.

**Comment by rtfb** [comment]
There's no plan for it. I would actually consider it harmful to include such inverted functionality into Blackfriday itself. I can imagine some code reuse, though. Let's say, after #370 is done, a package that renders AST to markdown could be reused. Then the HTML-to-MD converter could parse HTML, transform DOM to Blackfriday's AST, and call the MD renderer. But I expect the transformation code would be by far the most difficult part of it, so such a reuse wouldn't even save much effort.
