### ISSUE TITLE
Add flag HTML_NOOPENER_LINKS to create absolute links with "noopener" rel attribute

### ISSUE THREAD

**Issue by stefanneuhaus** [russross/blackfriday#459]
There are already the following flags that add a certain value to the "rel" attribute of absolute links:
* HTML_NOREFERRER_LINKS: "noreferrer"
* HTML_NOFOLLOW_LINKS: "nofollow"

At least for the following reasons it would be desirable to have a flag that also adds a "noopener" value to the "rel" attribute:
* Security: see [About rel=noopener](https://mathiasbynens.github.io/rel-noopener/)
* Performance: see [The performance benefits of rel=noopener](https://jakearchibald.com/2016/performance-benefits-of-rel-noopener/)

The request is to add the flag HTML_NOOPENER_LINKS that implements this.

**Comment by rtfb** [comment]
For reference, this is [already implemented](https://github.com/russross/blackfriday/pull/437) in v2, and only needs backporting.
