### ISSUE TITLE
The character of '#' in code block

### ISSUE THREAD

**Issue by SmartBrave** [russross/blackfriday#460]
I was written the C code with markdown:

\`\`\` C
#include<stdio.h>

int main(){
    return;
}
\`\`\`

The first line could be explain to '\<h1\>include<stdio.h>\</h1\>' , but I want to keep '#' in code block. It's a BUG or not ?

**Comment by rtfb** [comment]
Did you specify `EXTENSION_FENCED_CODE` (if you're using version 1) or `FencedCode` (if version 2)?

**Comment by SmartBrave** [comment]
yeah, I'm not. And I try it now, the result is success! Thank you!
