### ISSUE TITLE
Render tree back to markdown

### ISSUE THREAD

**Issue by FedorZaytsev** [russross/blackfriday#461]
Is there any way to render parsed markdown text back into markdown without writing my own renderer?

**Comment by rtfb** [comment]
Yes, kinda. @shurcooL has written this tool: https://github.com/shurcooL/markdownfmt, it's like `gofmt`, but for Markdown. So it renders back into markdown, but may alter the original towards some standard. This may, or may not be what you're after.

There's also this tracking issue #370, but there was no good progress for it.
