### ISSUE TITLE
# in <pre><code> missinterpreted

### ISSUE THREAD

**Issue by somenxavier** [russross/blackfriday#47]
If you put "#" in <pre><code>, then the symbol is interpreted as header.

See [this](https://github.com/piranha/gostatic/issues/17#issuecomment-31113743)

Thanks,

**Comment by rtfb** [comment]
It works fine if you use the `EXTENSION_LAX_HTML_BLOCKS` extension:

```go
func TestRepro(t *testing.T) {
	var tests = []string{
		`* hi
<pre>
<code>
# hi
</code>
</pre>
* ho
`,
		`<ul>
<li><p>hi</p>

<pre>
<code>
# hi
</code>
</pre></li>

<li><p>ho</p></li>
</ul>
`,
	}
	doTestsInlineParam(t, tests, Options{
		Extensions: EXTENSION_LAX_HTML_BLOCKS,
	}, 0, HtmlRendererParameters{})
}
```

Note: if you remove the `Extensions: EXTENSION_LAX_HTML_BLOCKS,` line, the problem will reproduce just like you described.

**Comment by rtfb** [comment]
Alternatively, this also works correctly, as per description in the original Markdown [spec](https://daringfireball.net/projects/markdown/syntax):

> List items may consist of multiple paragraphs. Each subsequent paragraph in a list item must be indented by either 4 spaces or one tab

```go
func TestRepro(t *testing.T) {
	var tests = []string{
		`*   hi

    <pre>
    <code>
    # hi
    </code>
    </pre>

* ho
`,
		`<ul>
<li><p>hi</p>

<pre>
<code>
# hi
</code>
</pre></li>

<li><p>ho</p></li>
</ul>
`,
	}
	doTestsInlineParam(t, tests, Options{
	//Extensions: EXTENSION_LAX_HTML_BLOCKS,
	}, 0, HtmlRendererParameters{})
}
```

Note: I have indented "hi" to 4th column, all of the `<pre>` block to 4th column, and added blank lines around the `<pre>` block; no extension needed in this case.

I consider the issue closed.

**Comment by piranha** [comment]
Hey, so I've tried this thing with EXTENSION_LAX_HTML_BLOCKS and it didn't work for me, `# hi` was still rendered as a header rather than code.

**Comment by rtfb** [comment]
I just tried the above code and it still works as I described. Can you post yours?
