### ISSUE TITLE
github flavored Markdown configuration in core

### ISSUE THREAD

**Issue by ibes** [russross/blackfriday#48]
Hi,

there are two out of the box configurations how markdown may be rendered Basic and Common. 

GitHub does some things different than the standard markdown - for example a line break in Markdown is a link break in HTML. 

blackfriday has everything that is needed to make a markdownGHF configuration. 
As this configuration is quite popular it would be nice to have this as a third out of the box configuration.

The documentation about how to implement it for my own is not clear enough for me - maybe a clearer documentation would be an other good solution.

This would be the extension set for it

````
EXTENSION_NO_INTRA_EMPHASIS
EXTENSION_HARD_LINE_BREAK
EXTENSION_AUTOLINK
EXTENSION_STRIKETHROUGH
EXTENSION_FENCED_CODE
````
see: https://help.github.com/articles/github-flavored-markdown

**Comment by shurcooL** [comment]
If I'm reading the dates correctly, this issue has been resolved since my last comment here.

Resolved via #93. There's now a GitHub Flavored Markdown renderer that you can use.

Please feel free to re-open if you have further comments.
