### ISSUE TITLE
PDF output

### ISSUE THREAD

**Issue by BenjaminRH** [russross/blackfriday#66]
Any thoughts on supporting PDF output as well?

**Comment by porjo** [comment]
+1 for PDF output. [gopdf](http://github.com/signintech/gopdf) library provides PDF output but not sure how suitable it would be for this application.

**Comment by rtfb** [comment]
Since we have decided we're not incorporating any more renderers into the core library, I'm closing this. If anyone implements that as a separate renderer, we'll gladly add a link to it in the README.

**Comment by pjebs** [comment]
Does anyone know the difference between https://github.com/jung-kurt/gofpdf and https://github.com/signintech/gopdf?
