### ISSUE TITLE
Add LaTeX Options for skipping header and footer

### ISSUE THREAD

**Issue by LimEJET** [russross/blackfriday#80]
As for now this can be circumvented by shadowing the header and footer methods with stubs, but it'd be more convenient if there was an option similar to the "generate complete html document" thing for html output.

**Comment by Ambrevar** [comment]
My renderer implements this: https://bitbucket.org/ambrevar/blackfriday-latex

**Comment by shurcooL** [comment]
Sounds good. I'll close this, since it seems there's nothing actionable left to do here. Feel free to re-open if needed.
