### ISSUE TITLE
blackfriday produces invalidly nested HTML.

### ISSUE THREAD

**Issue by buro9** [russross/blackfriday#99]
I'm noticing more and more that for various input blackfriday can produce HTML that is invalidly nested and that may break the layout of the page on which it appears.

Input:
```markdown
<blockquote>
A list:
1. Foo</blockquote>
1. Bar
```

Which is a valid HTML blockquote containing a list with Foo, and outside of the blockquote a list with Bar.

Expected (something like):
```html
<blockquote>
A list:
<ol>
<li>Foo<br/></li>
</ol>
</blockquote>
<ol>
<li>Bar</li>
</ol>
```

Output:
```html
<blockquote><br/>
A list:</p>

<ol>
<li>Foo</blockquote><br/></li>
<li>Bar<br/></li>
</ol>
```

Note that the blockquote is now terminated within the list item, forcing the browser to close tags wherever it feels suitable, which then introduces phantom tags which will change the page layout.

Question: Is it the job of blackfriday to produce valid HTML?

**Comment by rtfb** [comment]
> blackfriday should produce valid HTML for valid input

Yes, it should. But this particular case doesn't seem to be a valid input, as per [spec](https://daringfireball.net/projects/markdown/syntax#html):

> The only restrictions are that block-level HTML elements — e.g. `<div>`, `<table>`, `<pre>`, `<p>`, etc. — must be separated from surrounding content by blank lines, and the start and end tags of the block should not be indented with tabs or spaces.

At the very least, a blank line is missing after the `</blockquote>`, but the "not be indented with tabs or spaces" bit can also be interpreted to mean that the close tag can not have preceding text either.

I lean towards closing this one as WAD.

**Comment by shurcooL** [comment]
I tend to agree. At least I don't really see any actionable resolutions for this.
